/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 campus.glb 
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { Route, Routes, useNavigate } from 'react-router-dom';
import { useSharedState } from './sharedState';
import { PresentationControls } from '@react-three/drei';

export function Campus(props) {
  const { nodes, materials } = useGLTF('/campus.glb')
  const { setText, setDesc } = useSharedState();
  function clear() {
    setText('');

  }
  return (
    <RigidBody type="fixed">
      <group {...props} dispose={null} position={[0, -20, 0]} scale={7} rotation={[0, -Math.PI / 2, 0]}>
        <group position={[-40.038, 0.197, -12.731]} rotation={[-Math.PI / 2, 0, 0]} scale={0.682}>
          <group rotation={[Math.PI / 2, 0, 0]}>
          {/* <RigidBody type="mesh"> */}
            <mesh geometry={nodes.court_court_0.geometry} material={materials.court} position={[13.781, 0, -11.633]} rotation={[0, -0.003, 0]} scale={0.611} />
            <mesh geometry={nodes.court_gray_metalic_0.geometry} material={materials.gray_metalic} position={[13.781, 0, -11.633]} rotation={[0, -0.003, 0]} scale={0.611} />
            <mesh geometry={nodes.court_gray_metalic_0001.geometry} material={materials.gray_metalic} position={[13.781, 0, -11.633]} rotation={[0, -0.003, 0]} scale={0.611} />
            <mesh geometry={nodes.court_kale_diregi_0.geometry} material={materials.kale_diregi} position={[13.781, 0, -11.633]} rotation={[0, -0.003, 0]} scale={0.611} />
            <mesh geometry={nodes.court_spot_light_0.geometry} material={materials.spot_light} position={[13.781, 0, -11.633]} rotation={[0, -0.003, 0]} scale={0.611} />
          {/* </RigidBody> */}
          </group>
        </group>
        <group position={[-10.795, 0.466, -0.965]} rotation={[-Math.PI / 2, 0, 0]} scale={0.418}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[0, 3.278, 0]} scale={[0.302, 1.009, 0.302]}>
              <mesh
                geometry={nodes.Object_4.geometry} material={materials['Material.042']} position={[0, -2.097, 0]} scale={[1, 0.539, 1]} />
              <mesh geometry={nodes.Object_5.geometry} material={materials['Material.043']} position={[0, -1.701, 0]} scale={[1, 0.539, 1]} />
            </group>
          </group>
        </group>

        <group position={[-23.244, 0.151, -0.734]} rotation={[-Math.PI / 2, 0, 1.567]} scale={[0.002, 0.002, 0.004]}>
          <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.98}>
            <group onPointerEnter={(e) => setText('Admistrative Block')}
              onPointerLeave={(e) => clear()}
              position={[0, 0, -0.001]}>
              <mesh geometry={nodes.Plane004_white_0.geometry} material={materials['Material.007']} position={[-15.585, 335.45, -554.261]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane002_red_0.geometry} material={materials.material} position={[5496.594, 613.064, -724.42]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane003_red_0.geometry} material={materials.material} position={[-5540.824, 613.591, -757.926]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane005_red_0.geometry} material={materials.material} position={[1340.128, 1021.341, -4311.112]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane006_white_0.geometry} material={materials.white} position={[190.225, 149.651, -3922.777]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane007_black_0.geometry} material={materials.black} position={[-2055.37, 811.428, -3071.987]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane008_red_0.geometry} material={materials.material} position={[48.638, 710.256, -40.203]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane009_black_0.geometry} material={materials.black} position={[2031.53, 947.597, -3070.033]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane010_black2_0.geometry} material={materials.black2} position={[53.016, 580, 2261.104]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane011_black_0.geometry} material={materials.black} position={[0, 612.605, -1565.424]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane012_red_0.geometry} material={materials.material} position={[9.792, 610, -2740.975]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane013_black_0.geometry} material={materials.black} position={[-5026.123, 780, 1266.117]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane014_black_0.geometry} material={materials.black} position={[-5226.327, 780, -3598.718]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane015_black_0.geometry} material={materials.black} position={[4983.868, 780, 1343.825]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane016_black_0.geometry} material={materials.black} position={[5184.071, 780, -3521.005]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane017_black_0.geometry} material={materials.black} position={[-21.127, 581.204, -1038.526]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane018_black_0.geometry} material={materials.black} position={[33.142, 595.862, 1462.004]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane019_black_0.geometry} material={materials.black} position={[-14.299, 500, -763.371]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane020_red_0.geometry} material={materials.material} position={[2797.298, 241.483, 2486.363]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane021_red_0.geometry} material={materials.material} position={[-2808.908, 239.335, 2617.57]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane022_orange_0.geometry} material={materials.orange} position={[52.534, 364.347, 2657.307]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane023_orange_0.geometry} material={materials.orange} position={[6.364, 122.916, 3713.022]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane030_blue_0.geometry} material={materials.blue} position={[0, 19.649, 3664.5]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane031_red_0.geometry} material={materials.material} position={[-1384.612, 913.9, -4253.547]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane032_black_0.geometry} material={materials.black} position={[-21.127, 536.696, -998.139]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane033_black_0.geometry} material={materials.black} position={[54.379, 830, 603.302]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane034_white_0.geometry} material={materials.white} position={[6.364, 961.125, 3713.025]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
              <mesh geometry={nodes.Plane035_white_0.geometry} material={materials.white} position={[4184.385, 420, -65.55]} rotation={[-Math.PI / 2, 0, 0]} scale={[175.595, 100, 100]} />
            </group>
          </group>
        </group>
        <group position={[17.312, 16.23, 48.446]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.096, 0.096, 0.116]}>
          <group position={[-358.902, 301.263, -112.017]} rotation={[-Math.PI / 2, 0.721, -Math.PI]} scale={[1.071, 1.673, 1.071]}>
            <mesh

              onPointerEnter={(e) => setText('Biology Block')}
              onPointerLeave={(e) => clear()}

              geometry={nodes.Torus_026_Torus_001_0.geometry} material={materials.build_mat} />
            <mesh geometry={nodes.Torus_026_Torus_001_1.geometry} material={materials.glaze2} />
            <mesh geometry={nodes.Torus_026_Torus_001_2.geometry} material={materials['grass.001']} />
            <mesh geometry={nodes.Torus_026_Torus_001_3.geometry} material={materials.lights_1} />
            <mesh geometry={nodes.Torus_026_Torus_001_4.geometry} material={materials.water} />
            <mesh geometry={nodes.Torus_026_Torus_001_5.geometry} material={materials.floor} />
          </group>
          <mesh geometry={nodes.Sphere_015_Sphere_001001.geometry} material={materials.tree} position={[-358.132, 282.92, -130.125]} rotation={[-Math.PI / 2, 0.721, -Math.PI]} scale={[1.071, 1.673, 1.071]} />
          <mesh geometry={nodes.Sphere_016_Sphere_001001.geometry} material={materials.tree} position={[-342.985, 312.971, -126.598]} rotation={[-Math.PI / 2, 0.721, -Math.PI]} scale={[1.071, 1.673, 1.071]} />
          <mesh geometry={nodes.Sphere_017_Sphere_001001.geometry} material={materials.tree} position={[-383.298, 319.426, -130.125]} rotation={[-Math.PI / 2, 0.721, -Math.PI]} scale={[1.071, 1.673, 1.071]} />
          <mesh geometry={nodes.Sphere_018_Sphere_001001.geometry} material={materials.tree} position={[-336.946, 322.543, -134.987]} rotation={[-Math.PI / 2, 0.721, -Math.PI]} scale={[1.071, 1.673, 1.071]} />
          <mesh geometry={nodes.Torus_013_Torus_001_2.geometry} material={materials.floor} position={[-51.007, -155.513, 101.189]} rotation={[1.571, 1.555, 0]} />
          <mesh geometry={nodes.Torus_013_Torus_005_2.geometry} material={materials.floor} position={[186.036, -36.001, 101.189]} rotation={[1.571, 1.555, 0]} />
        </group>
        <group position={[-69.022, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.039}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_4001.geometry} material={materials.material_0} position={[-305.797, -480.887, 0]} rotation={[0, 0, -0.112]} scale={[1, 1.188, 1]} />
          </group>
        </group>
        <group position={[-18.164, 0.149, -20.952]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.001, 0.001, 0.002]}>
          <group position={[0.004, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <group position={[-0.004, 0, -0.002]}>
              <group position={[-0.004, 0, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <group position={[0, 0, 1]}>
                  <mesh

                    onPointerEnter={(e) => setText('Chemistry Block')}
                    onPointerLeave={(e) => clear()}
                    geometry={nodes.Stadium_Upper_Placeable_0.geometry} material={materials.Placeable} />
                  <mesh geometry={nodes.Stadium_Upper_TransparentDisplay_0.geometry} material={materials.TransparentDisplay} />
                </group>
                <mesh onPointerEnter={(e) => setText('Chemistry Block')}
                  onPointerLeave={(e) => clear()}
                  geometry={nodes.Stadium_Body_Placeable_0.geometry} material={materials.Placeable} position={[0, 0, 1]} />
                <mesh onPointerEnter={(e) => setText('Chemistry Block')}
                  onPointerLeave={(e) => clear()}
                  geometry={nodes.Stadium_Door_Placeable_0.geometry} material={materials.Placeable} />
                <mesh onPointerEnter={(e) => setText('Chemistry Block')}
                  onPointerLeave={(e) => clear()}
                  geometry={nodes.Stadium_Foundation_Placeable_0.geometry} material={materials.Placeable} position={[0, 0, 1]} />
                <mesh onPointerEnter={(e) => setText('Chemistry Block')}
                  onPointerLeave={(e) => clear()}
                  geometry={nodes.Stadium_Inside_Placeable_0.geometry} material={materials.Placeable} position={[0, 0, 1]} />
                <mesh onPointerEnter={(e) => setText('Chemistry Block')}
                  onPointerLeave={(e) => clear()}
                  geometry={nodes.Stadium_Parts_Placeable_0.geometry} material={materials.Placeable} position={[0, 0, 1]} />
              </group>
            </group>
          </group>
        </group>
        <group position={[-1.403, 0, 26.303]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0.geometry} material={materials['Fence.002']} position={[-5.892, 0, 0]} scale={[0.89, 1, 1]} />
          </group>
        </group>
        <group position={[15.128, 0, -19.799]} rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group position={[0, 0, 0]}>
              <group position={[0.001, 0, 0]}>
                <mesh
                  onPointerEnter={(e) => setText('Space Block')}
                  onPointerLeave={(e) => clear()}
                  geometry={nodes.Building3_metalwalls_0.geometry} material={materials.metalwalls} position={[-5800.155, -300.114, 100.305]} rotation={[0, -0.752, 0]} scale={[2.353, 1.284, 2.353]} />

              </group>
            </group>
          </group>
        </group>
        {/* <group position={[-40.178, 0, 16.422]} rotation={[-Math.PI / 2, 0, 2.597]} scale={0.32}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 2.402]}>
            <mesh geometry={nodes.Object_7.geometry} material={materials.lantai} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.screen_pinggir} />
          </group>
          <mesh geometry={nodes.Object_13.geometry} material={materials.lantai} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.lantai} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.screen_pinggir} />
          <mesh geometry={nodes.Object_4004.geometry} material={materials.lantai} />
          <mesh geometry={nodes.Object_5001_1.geometry} material={materials.light_lanta} />
        </group>
      </group> */}
        <group position={[0.731, 0, 1.732]} rotation={[0, 1.569, 0]} scale={0.202}>
          <mesh sensor onIntersectionEnter={() => { console.log("jkn"); window.location.href = '/Digestive'; }} geometry={nodes.Gate001.geometry} material={materials['_Black.027']} position={[0, 0.667, 0]} scale={1.604} />
          <mesh geometry={nodes.Gate002.geometry} material={materials['_White.023']} position={[0, 0.667, 0]} scale={1.604} />
          <group position={[0, 0.667, 0]} scale={1.604}>
            <mesh geometry={nodes.Plane_1.geometry} material={materials['_White.023']} />
            <mesh sensor onIntersectionEnter={() => { console.log("jkn"); window.location.href = '/Digestive'; }} geometry={nodes.Plane_2.geometry} material={materials['_Black.027']} />
          </group>
          <mesh sensor onIntersectionEnter={() => { console.log("jkn"); window.location.href = '/Digestive'; }} geometry={nodes.Gate004.geometry} material={materials['_Black.027']} position={[0, 0.667, 0]} scale={1.604} />
          <mesh geometry={nodes.m3d.geometry} material={materials['_White.022']} position={[0, 1.39, 0]} scale={1.604} />
        </group>
        <group position={[-1.403, 0, 26.303]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0001.geometry} material={materials['Fence.001']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-6.387, 0, 26.303]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0002.geometry} material={materials['Fence.003']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-11.373, 0, 26.303]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0003.geometry} material={materials['Fence.004']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-16.361, 0, 26.303]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0004.geometry} material={materials['Fence.005']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-21.35, 0, 26.303]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0005.geometry} material={materials['Fence.006']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-26.322, 0, 26.303]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0006.geometry} material={materials['Fence.007']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-31.303, 0, 26.303]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0007.geometry} material={materials['Fence.008']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-36.28, 0, 26.303]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0008.geometry} material={materials['Fence.009']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-41.256, 0, 26.303]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0009.geometry} material={materials['Fence.010']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-48.658, 0, 28.729]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0010.geometry} material={materials['Fence.011']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-48.658, 0, 23.773]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0011.geometry} material={materials['Fence.012']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-48.658, 0, 18.828]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0012.geometry} material={materials['Fence.013']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-48.658, 0, 13.835]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0013.geometry} material={materials['Fence.014']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-48.658, 0, 8.854]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0014.geometry} material={materials['Fence.015']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-48.658, 0, 3.905]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0015.geometry} material={materials['Fence.016']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-48.658, 0, -1.073]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0016.geometry} material={materials['Fence.017']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-48.658, 0, -6.051]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0017.geometry} material={materials['Fence.018']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-48.658, 0, -11.028]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0018.geometry} material={materials['Fence.019']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-48.658, 0, -16.052]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0019.geometry} material={materials['Fence.020']} position={[-129.449, 0, -0.001]} />
          </group>
        </group>
        <group position={[-48.658, 0, -20.986]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0020.geometry} material={materials['Fence.021']} position={[-94.47, 0, -0.041]} rotation={[-Math.PI, 0, 0]} scale={[-0.516, -1, -1]} />
          </group>
        </group>
        <group position={[-41.256, 0, -25.988]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0021.geometry} material={materials['Fence.022']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-36.28, 0, -25.988]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0022.geometry} material={materials['Fence.023']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-31.303, 0, -25.988]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0023.geometry} material={materials['Fence.024']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-26.322, 0, -25.988]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0024.geometry} material={materials['Fence.025']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-21.35, 0, -25.988]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0025.geometry} material={materials['Fence.026']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-16.361, 0, -25.988]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0026.geometry} material={materials['Fence.027']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-11.373, 0, -25.988]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0027.geometry} material={materials['Fence.028']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-6.387, 0, -25.988]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0028.geometry} material={materials['Fence.029']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-1.403, 0, -25.988]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0029.geometry} material={materials['Fence.030']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-1.403, 0, -25.988]} rotation={[-Math.PI / 2, 0, 0]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0030.geometry} material={materials['Fence.031']} position={[-3.467, 0, 0]} scale={[0.941, 1, 1]} />
          </group>
        </group>
        <group position={[0.657, 0, -16.052]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0031.geometry} material={materials['Fence.032']} position={[-129.449, 0, -0.001]} />
          </group>
        </group>
        <group position={[0.657, 0, -11.028]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0032.geometry} material={materials['Fence.033']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[0.657, 0, -6.051]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0033.geometry} material={materials['Fence.034']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[0.657, 0, 3.905]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0035.geometry} material={materials['Fence.036']} position={[-728.436, 0, 0.677]} />
          </group>
        </group>
        <group position={[0.657, 0, 8.854]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0036.geometry} material={materials['Fence.037']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[0.657, 0, 13.835]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0037.geometry} material={materials['Fence.038']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[0.657, 0, 18.828]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0038.geometry} material={materials['Fence.039']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[0.657, 0, 23.773]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0039.geometry} material={materials['Fence.040']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[0.657, 0, 28.729]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0040.geometry} material={materials['Fence.041']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[0.657, 0, -2.276]} rotation={[-Math.PI / 2, 0, -1.572]} scale={3.8}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Fense_Fence002_0034.geometry} material={materials['Fence.042']} position={[-130.547, 0, 0]} />
          </group>
        </group>
        <group position={[-38.631, 0, -54.105]} rotation={[-Math.PI / 2, 0, -1.537]} scale={0.039}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_4002.geometry} material={materials['material_0.001']} position={[-69.572, -492.787, -268.659]} rotation={[0, 0, -0.112]} scale={[1, 1.188, 1]} />
          </group>
        </group>
        <group position={[-40.043, 0, 45.886]} rotation={[-Math.PI / 2, 0, 1.54]} scale={0.039}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_4003.geometry} material={materials['material_0.003']} position={[-293.796, -484.491, 388.79]} rotation={[0, 0, -0.112]} scale={[1, 1.188, 1]} />
          </group>
        </group>
        <group position={[-94.021, 0, -54.105]} rotation={[-Math.PI / 2, 0, -1.537]} scale={0.039}>
          <group position={[0, 0.001, 0]}>
            <group rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Object_4006.geometry} material={materials['material_0.002']} position={[-69.572, -492.787, -268.658]} rotation={[0, 0, -0.112]} scale={[1, 1.188, 1]} />
            </group>
          </group>
        </group>
        <group position={[-94.021, 0, 60.475]} rotation={[-Math.PI / 2, 0, -1.537]} scale={0.039}>
          <group position={[0, 0, 0]}>
            <group rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Object_4007.geometry} material={materials['material_0.004']} position={[-69.572, -492.787, -268.659]} rotation={[0, 0, -0.112]} scale={[1, 1.188, 1]} />
            </group>
          </group>
        </group>
        <group position={[25, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_10009.geometry} material={materials.Kust_1} />
          <mesh geometry={nodes.Object_11001.geometry} material={materials.Kust_2} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.Paporotnik} />
          <mesh geometry={nodes.Object_13001.geometry} material={materials['Wood_tree.001']} />
          <mesh geometry={nodes.Object_14006.geometry} material={materials['Wood_tree.002']} />
          <mesh geometry={nodes.Object_2.geometry} material={materials.Floor} />
          <mesh geometry={nodes.Object_3001.geometry} material={materials.Green_Elka} />
          <mesh geometry={nodes.Object_4008.geometry} material={materials.Green_Elka} />
          <mesh geometry={nodes.Object_5002.geometry} material={materials.Green_Elka} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Green_Elka} />
          <mesh geometry={nodes.Object_7001.geometry} material={materials.Green_Elka} />
          <mesh geometry={nodes.Object_8001.geometry} material={materials['Green_sosna.001']} />
          <mesh geometry={nodes.Object_9.geometry} material={materials['Green_sosna.001']} />
        </group>
        <group position={[25, 0, 29]} rotation={[-Math.PI / 2, 0, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_10010.geometry} material={materials.Kust_1} />
          <mesh geometry={nodes.Object_11002.geometry} material={materials.Kust_2} />
          <mesh geometry={nodes.Object_12001.geometry} material={materials.Paporotnik} />
          <mesh geometry={nodes.Object_13002.geometry} material={materials['Wood_tree.001']} />
          <mesh geometry={nodes.Object_14007.geometry} material={materials['Wood_tree.002']} />
          <mesh geometry={nodes.Object_2001.geometry} material={materials.Floor} />
          <mesh geometry={nodes.Object_3002.geometry} material={materials.Green_Elka} />
          <mesh geometry={nodes.Object_4009.geometry} material={materials.Green_Elka} />
          <mesh geometry={nodes.Object_5003.geometry} material={materials.Green_Elka} />
          <mesh geometry={nodes.Object_6001.geometry} material={materials.Green_Elka} />
          <mesh geometry={nodes.Object_7002.geometry} material={materials.Green_Elka} />
          <mesh geometry={nodes.Object_8002.geometry} material={materials['Green_sosna.001']} />
          <mesh geometry={nodes.Object_9001.geometry} material={materials['Green_sosna.001']} />
        </group>
        <group position={[25, 0, -29]} rotation={[-Math.PI / 2, 0, 0]} scale={1.832}>
          <mesh geometry={nodes.Object_10011.geometry} material={materials.Kust_1} />
          <mesh geometry={nodes.Object_11003.geometry} material={materials.Kust_2} />
          <mesh geometry={nodes.Object_12002.geometry} material={materials.Paporotnik} />
          <mesh geometry={nodes.Object_13003.geometry} material={materials['Wood_tree.001']} />
          <mesh geometry={nodes.Object_14008.geometry} material={materials['Wood_tree.002']} />
          <mesh geometry={nodes.Object_2002.geometry} material={materials.Floor} />
          <mesh geometry={nodes.Object_3003.geometry} material={materials.Green_Elka} />
          <mesh geometry={nodes.Object_4010.geometry} material={materials.Green_Elka} />
          <mesh geometry={nodes.Object_5004.geometry} material={materials.Green_Elka} />
          <mesh geometry={nodes.Object_6002.geometry} material={materials.Green_Elka} />
          <mesh geometry={nodes.Object_7003.geometry} material={materials.Green_Elka} />
          <mesh geometry={nodes.Object_8003.geometry} material={materials['Green_sosna.001']} />
          <mesh geometry={nodes.Object_9002.geometry} material={materials['Green_sosna.001']} />
        </group>
        <mesh

          onPointerEnter={(e) => setText('TelePort')}
          onPointerLeave={(e) => clear()} geometry={nodes.Sphere_019_Sphere_002_0.geometry} material={materials['build_mat.001']} position={[-6.257, 1.137, 7.444]} rotation={[Math.PI, -0.651, Math.PI]} scale={0.158} />
        <mesh
          onPointerEnter={(e) => setText('TelePort')}
          onPointerLeave={(e) => clear()} geometry={nodes.Sphere_019_Sphere_002_0001.geometry} material={materials['build_mat.001']} position={[-6.257, 1.137, 7.444]} rotation={[Math.PI, -0.651, Math.PI]} scale={0.158} />
        <mesh
          onPointerEnter={(e) => setText('TelePort')}
          onPointerLeave={(e) => clear()} geometry={nodes.Sphere_019_Sphere_002_0002.geometry} material={materials['build_mat.001']} position={[-6.257, 1.137, 7.444]} rotation={[Math.PI, -0.651, Math.PI]} scale={0.158} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.glaze} position={[-72.446, 0.522, 1.102]} rotation={[-1.612, 0, 0]} scale={[0.346, 0.347, 0.56]} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.mullion} position={[-72.446, 0.522, 1.102]} rotation={[-1.612, 0, 0]} scale={[0.346, 0.347, 0.56]} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.mesh_1} position={[-72.446, 0.522, 1.102]} rotation={[-1.612, 0, 0]} scale={[0.346, 0.347, 0.56]} />
        <mesh geometry={nodes.Object_96.geometry} material={materials.mesh_1} position={[-72.446, 0.522, 1.102]} rotation={[-1.612, 0, 0]} scale={[0.346, 0.347, 0.56]} />
        <mesh geometry={nodes.Object_98.geometry} material={materials.mesh_1} position={[-72.446, 0.522, 1.102]} rotation={[-1.612, 0, 0]} scale={[0.346, 0.347, 0.56]} />
        <mesh geometry={nodes.Object_4005.geometry} material={materials['Material.001']} position={[-13.097, 0, -1848.919]} />
        {/* <RigidBody type='mesh'> */}
        <mesh geometry={nodes.Object_10001.geometry} material={materials.Trek_Material_free} position={[-8.449, 0.216, 1.437]} rotation={[-Math.PI, 1.552, -Math.PI]} scale={0.189} />
        <mesh geometry={nodes.Object_10002.geometry} material={materials.Trek_Material_free} position={[-13.71, 0.216, 1.554]} rotation={[0, 0.035, 0]} scale={0.189} />
        <mesh geometry={nodes.Object_10003.geometry} material={materials.Trek_Material_free} position={[-13.869, 0.216, -3.39]} rotation={[0, -1.516, 0]} scale={0.189} />
        <mesh geometry={nodes.Object_10004.geometry} material={materials.Trek_Material_free} position={[-8.57, 0.216, -3.59]} rotation={[Math.PI, -0.033, Math.PI]} scale={0.189} />
        <mesh geometry={nodes.Object_10005.geometry} material={materials.Trek_Material_free} position={[-11.8, 0.216, -14.736]} rotation={[Math.PI, -0.033, Math.PI]} scale={0.189} />
        <mesh geometry={nodes.Object_10006.geometry} material={materials.Trek_Material_free} position={[-37.773, 0.216, -14.694]} rotation={[0, -1.564, 0]} scale={0.189} />
        <mesh geometry={nodes.Object_10007.geometry} material={materials.Trek_Material_free} position={[-37.612, 0.216, 13.503]} rotation={[0, 0.02, 0]} scale={0.189} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Trek_Material_free} position={[-8.304, 0.216, -1.081]} rotation={[3.138, -0.013, 3.141]} scale={0.189} />
        <mesh geometry={nodes.Object_14001.geometry} material={materials.Trek_Material_free} position={[-14.007, 0.216, -1.008]} rotation={[3.138, -0.013, 3.141]} scale={0.189} />
        <mesh geometry={nodes.Object_14002.geometry} material={materials.Trek_Material_free} position={[-11.546, 0.216, -9.087]} rotation={[3.138, -0.013, 3.141]} scale={[0.189, 0.189, 0.603]} />
        <mesh geometry={nodes.Object_14003.geometry} material={materials.Trek_Material_free} position={[-37.935, 0.216, -0.585]} rotation={[3.138, -0.004, 3.141]} scale={[0.189, 0.189, 1.721]} />
        <mesh geometry={nodes.Object_14004.geometry} material={materials.Trek_Material_free} position={[-11.335, 0.216, 7.36]} rotation={[3.138, -0.013, 3.141]} scale={[0.189, 0.189, 0.656]} />
        <mesh geometry={nodes.Object_16001.geometry} material={materials.Trek_Material_free} position={[-3.85, 0.216, -1.033]} rotation={[-3.14, 1.564, 3.139]} scale={[0.189, 0.189, 0.241]} />
        <mesh geometry={nodes.Object_16002.geometry} material={materials.Trek_Material_free} position={[-11.094, 0.216, 1.713]} rotation={[-3.14, 1.564, 3.139]} scale={[0.189, 0.189, 0.099]} />
        <mesh geometry={nodes.Object_16003.geometry} material={materials.Trek_Material_free} position={[-11.173, 0.216, -3.717]} rotation={[-3.141, 1.547, 3.14]} scale={[0.189, 0.189, 0.11]} />
        <mesh geometry={nodes.Object_16004.geometry} material={materials.Trek_Material_free} position={[-24.743, 0.216, -14.903]} rotation={[-3.13, 1.57, 3.129]} scale={[0.189, 0.189, 0.792]} />
        <mesh geometry={nodes.Object_16005.geometry} material={materials.Trek_Material_free} position={[-24.624, 0.216, 13.678]} rotation={[-3.13, 1.57, 3.129]} scale={[0.189, 0.189, 0.795]} />

        {/* </RigidBody> */}
        <mesh geometry={nodes.Cube.geometry} material={materials['Material.002']} position={[-25.077, -0.315, 0.155]} scale={2.637} />
        <mesh geometry={nodes.Text012.geometry} material={nodes.Text012.material} position={[-8.638, 0.994, 17.634]} rotation={[Math.PI / 2, 0, 1.563]} scale={0.125} />
        <mesh geometry={nodes.Text011.geometry} material={nodes.Text011.material} position={[-7.384, 3.751, 15.991]} rotation={[Math.PI / 2, 0, -1.579]} scale={0.192} />
        <mesh geometry={nodes.Text010.geometry} material={nodes.Text010.material} position={[-7.619, 3.751, 15.404]} rotation={[Math.PI / 2, 0, 1.563]} scale={0.192} />
        <mesh geometry={nodes.Text009.geometry} material={nodes.Text009.material} position={[-7.466, 3.282, 15.915]} rotation={[Math.PI / 2, 0, -1.579]} scale={0.192} />
        <mesh geometry={nodes.Text008.geometry} material={nodes.Text008.material} position={[-7.619, 3.287, 15.404]} rotation={[Math.PI / 2, 0, 1.563]} scale={0.192} />
        <mesh geometry={nodes.Text007.geometry} material={materials['Material.046']} position={[-2.795, 3.115, 16.246]} rotation={[Math.PI / 2, 0, 3.134]} scale={0.649} />
        <group position={[-3.271, 2.156, 16.392]} rotation={[Math.PI / 2, 0, 3.134]} scale={0.473}>
          <mesh geometry={nodes.Plane117_1.geometry} material={materials['Material.047']} />
          <mesh geometry={nodes.Plane117_2.geometry} material={materials['Material.048']} />
        </group>
        <group position={[-7.873, 1.849, 17.328]} rotation={[Math.PI / 2, 0, 3.134]} scale={0.473}>
          <mesh geometry={nodes.Plane118_1.geometry} material={materials['Material.047']} />
          <mesh geometry={nodes.Plane118_2.geometry} material={materials['Material.048']} />
        </group>
        <group position={[-3.224, 3.756, 16.258]} rotation={[-3.142, 1.563, 1.571]} scale={[0.077, 0.077, 0.083]}>
          <mesh geometry={nodes.Plane119.geometry} material={materials.burger} />
          <mesh geometry={nodes.Plane119_1.geometry} material={materials['Material.049']} />
          <mesh geometry={nodes.Plane119_2.geometry} material={nodes.Plane119_2.material} />
          <mesh geometry={nodes.Plane119_3.geometry} material={materials['Material.050']} />
        </group>
        <group position={[-7.543, 4.377, 15.66]} rotation={[Math.PI, -0.008, Math.PI / 2]} scale={[0.061, 0.061, 0.066]}>
          <mesh geometry={nodes.Plane120.geometry} material={materials.burger} />
          <mesh geometry={nodes.Plane120_1.geometry} material={materials['Material.049']} />
          <mesh geometry={nodes.Plane120_2.geometry} material={nodes.Plane120_2.material} />
          <mesh geometry={nodes.Plane120_3.geometry} material={materials['Material.050']} />
        </group>
        <group position={[-6.336, 2.117, 16.894]} rotation={[Math.PI / 2, 0, 2.533]} scale={0.473}>
          <mesh geometry={nodes.Plane121.geometry} material={materials['Material.047']} />
          <mesh geometry={nodes.Plane121_1.geometry} material={materials['Material.048']} />
        </group>
        <mesh geometry={nodes.Plane009.geometry} material={materials['Material.051']} position={[-8.626, 1.821, 17.945]} rotation={[Math.PI, -0.008, Math.PI]} scale={0.061} />
        <group position={[-5.389, 0.901, 15.965]} rotation={[Math.PI, -0.008, Math.PI]} scale={0.264}>
          <mesh geometry={nodes.Icosphere001_1.geometry} material={materials.Plant} />
          <mesh geometry={nodes.Icosphere001_2.geometry} material={materials['barber shop ']} />
        </group>
        <group position={[-2.465, 0.901, 15.939]} rotation={[Math.PI, -0.008, Math.PI]} scale={0.264}>
          <mesh geometry={nodes.Icosphere002.geometry} material={materials['barber shop ']} />
          <mesh geometry={nodes.Icosphere002_1.geometry} material={materials.Plant} />
        </group>
        <group position={[-2.646, 2.671, 16.187]} rotation={[Math.PI / 2, 0, 3.134]} scale={[0.006, 0.175, 0.006]}>
          <mesh geometry={nodes.Cylinder008_1.geometry} material={materials['Material.052']} />
          <mesh geometry={nodes.Cylinder008_2.geometry} material={materials['Material.053']} />
        </group>
        <mesh geometry={nodes.Cylinder007.geometry} material={nodes.Cylinder007.material} position={[-7.498, 0.59, 15.68]} rotation={[Math.PI, -0.008, Math.PI]} scale={[0.016, 0.061, 0.016]} />
        <group position={[-8.656, 2.611, 18.742]} rotation={[Math.PI / 2, 0, 1.563]} scale={[0.004, 0.11, 0.004]}>
          <mesh geometry={nodes.Cylinder011.geometry} material={materials['Material.052']} />
          <mesh geometry={nodes.Cylinder011_1.geometry} material={materials['Material.053']} />
        </group>
        <group position={[-7.195, 2.409, 17.187]} rotation={[Math.PI / 2, 0, 3.134]} scale={[0.003, 0.097, 0.003]}>
          <mesh geometry={nodes.Cylinder010.geometry} material={materials['Material.052']} />
          <mesh geometry={nodes.Cylinder010_1.geometry} material={materials['Material.053']} />
        </group>
        <mesh geometry={nodes.Cube107.geometry} material={nodes.Cube107.material} position={[-6.69, 1.575, 17.067]} rotation={[Math.PI, -0.608, Math.PI]} scale={[0.074, 0.074, 0.018]} />
        <mesh geometry={nodes.Cube006.geometry} material={materials.arrow} position={[-8.627, 1.032, 17.902]} rotation={[Math.PI, -0.008, Math.PI]} scale={[0.033, 0.102, 0.308]} />
        <group position={[-8.523, 1.458, 19.514]} rotation={[0, 0.008, -Math.PI]} scale={[0.014, 0.021, 0.676]}>
          <mesh geometry={nodes.Cube103_1.geometry} material={materials['Material.054']} />
          <mesh geometry={nodes.Cube103_2.geometry} material={materials['Material.055']} />
        </group>
        <mesh geometry={nodes.Cube104.geometry} material={materials.arrow} position={[-7.501, 3.345, 15.594]} rotation={[Math.PI, -0.008, Math.PI]} scale={[0.06, 0.119, 0.36]} />
        <mesh geometry={nodes.Cube103.geometry} material={materials.arrow} position={[-7.507, 3.741, 15.7]} rotation={[Math.PI, -0.008, Math.PI]} scale={[0.152, 0.169, 0.495]} />
        <mesh geometry={nodes.Cube102.geometry} material={materials['Material.056']} position={[-7.498, 0.59, 15.68]} rotation={[Math.PI, -0.008, Math.PI]} scale={[0.346, 0.107, 0.346]} />
        <group position={[-2.934, 3.555, 19.996]} rotation={[0, -1.563, 1.571]} scale={[0.337, 0.294, 0.566]}>
          <mesh geometry={nodes.Cube085.geometry} material={materials['police string']} />
          <mesh geometry={nodes.Cube085_1.geometry} material={materials['Material.057']} />
          <mesh geometry={nodes.Cube085_2.geometry} material={materials['Material.058']} />
        </group>
        <group position={[-2.93, 3.555, 20.61]} rotation={[0, -1.563, 1.571]} scale={[0.337, 0.294, 0.566]}>
          <mesh geometry={nodes.Cube084.geometry} material={materials['police string']} />
          <mesh geometry={nodes.Cube084_1.geometry} material={materials['Material.057']} />
          <mesh geometry={nodes.Cube084_2.geometry} material={materials['Material.058']} />
        </group>
        <mesh geometry={nodes.Cube099.geometry} material={nodes.Cube099.material} position={[-8.523, 2.493, 19.514]} rotation={[Math.PI, -0.008, Math.PI]} scale={[0.061, 0.023, 0.738]} />
        <mesh geometry={nodes.Cube098.geometry} material={nodes.Cube098.material} position={[-8.666, 1.348, 19.537]} rotation={[Math.PI, -0.008, Math.PI]} scale={[0.537, 0.028, 0.725]} />
        <mesh geometry={nodes.Cube097.geometry} material={nodes.Cube097.material} position={[-7.955, 1.348, 19.532]} rotation={[Math.PI, -0.008, Math.PI]} scale={[0.537, 0.028, 0.725]} />
        <mesh geometry={nodes.Cube096.geometry} material={materials['Material.059']} position={[-5.337, 1.771, 18.694]} rotation={[Math.PI, -0.008, Math.PI]} scale={[-3.121, -1.252, -2.371]} />
        <group position={[-5.855, 3.023, 18.955]} rotation={[Math.PI, -0.008, Math.PI]} scale={[-3.308, -1.252, -2.513]}>
          <mesh
            onPointerEnter={(e) => setText('Canteen')}
            onPointerLeave={(e) => clear()} geometry={nodes.Cube024.geometry} material={materials['Material.060']} />
          <mesh geometry={nodes.Cube024_1.geometry} material={nodes.Cube024_1.material} />
        </group>
        <mesh geometry={nodes.Cube094.geometry} material={materials['Material.061']} position={[-5.337, 1.771, 18.694]} rotation={[Math.PI, -0.008, Math.PI]} scale={[-3.121, -1.252, -2.371]} />
        <group position={[-7.072, 2.321, -17.457]} scale={[0.094, 0.062, 0.065]}>
          <mesh

            onPointerEnter={(e) => setText('Contributers Block')}
            onPointerLeave={(e) => clear()}
            geometry={nodes.Plane124.geometry} material={materials['super market']} />
          <mesh geometry={nodes.Plane124_1.geometry} material={materials['Material.063']} />
        </group>
        <group position={[-4.007, 2.59, -17.671]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.28, 0.256, 0.712]}>
          <mesh geometry={nodes.Cube015_1.geometry} material={materials['supermarket frame']} />
          <mesh geometry={nodes.Cube015_2.geometry} material={materials['Material.064']} />
          <mesh geometry={nodes.Cube015_3.geometry} material={materials['Material.065']} />
        </group>
        <group position={[-4.007, 2.59, -17.144]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.28, 0.256, 0.712]}>
          <mesh geometry={nodes.Cube014_1.geometry} material={materials['supermarket frame']} />
          <mesh geometry={nodes.Cube014_2.geometry} material={materials['Material.064']} />
          <mesh geometry={nodes.Cube014_3.geometry} material={materials['Material.065']} />
        </group>
        <group position={[-9.967, 2.589, -20.074]} rotation={[0, 0, Math.PI / 2]} scale={[0.28, 0.37, 0.491]}>
          <mesh geometry={nodes.Cube013_1.geometry} material={materials['supermarket frame']} />
          <mesh geometry={nodes.Cube013_2.geometry} material={materials['Material.064']} />
          <mesh geometry={nodes.Cube013_3.geometry} material={materials['Material.065']} />
        </group>
        <group position={[-10.731, 2.589, -20.074]} rotation={[0, 0, Math.PI / 2]} scale={[0.28, 0.37, 0.491]}>
          <mesh geometry={nodes.Cube012_1.geometry} material={materials['supermarket frame']} />
          <mesh geometry={nodes.Cube012_2.geometry} material={materials['Material.064']} />
          <mesh geometry={nodes.Cube012_3.geometry} material={materials['Material.065']} />
        </group>
        <group position={[-6.554, 0.878, -17.278]} rotation={[0, 0, -Math.PI]} scale={[-1.833, -0.761, -0.005]}>
          <mesh geometry={nodes.Cube011_1.geometry} material={materials['supermarket glass']} />
          <mesh geometry={nodes.Cube011_2.geometry} material={materials['supermarket frame']} />
        </group>
        <group position={[-4.01, 0.878, -16.846]} rotation={[0, 0, -Math.PI]} scale={[-1.833, -0.761, -0.005]}>
          <mesh geometry={nodes.Cube010_1.geometry} material={materials['supermarket frame']} />
          <mesh geometry={nodes.Cube010_2.geometry} material={materials['supermarket glass']} />
        </group>
        <group position={[-9.086, 0.878, -16.838]} rotation={[0, 0, -Math.PI]} scale={[-1.833, -0.761, -0.005]}>
          <mesh geometry={nodes.Cube008_1.geometry} material={materials['supermarket glass']} />
          <mesh geometry={nodes.Cube008_2.geometry} material={materials['supermarket frame']} />
        </group>
        <mesh geometry={nodes.Cube008.geometry} material={materials['Material.066']} position={[-7.158, 2.245, -17.016]} scale={[1.393, 0.305, 0.55]} />
        <group position={[-7.147, 0.413, -18.765]} scale={[0.094, 0.062, 0.065]}>
          <mesh
            onPointerEnter={(e) => setText('Contributers Block')}
            onPointerLeave={(e) => clear()}
            geometry={nodes.Cube016.geometry} material={materials['super market']} />
          <mesh
            onPointerEnter={(e) => setText('Contributers Block')}
            onPointerLeave={(e) => clear()}
            geometry={nodes.Cube016_1.geometry} material={materials['super market border']} />
        </group>
        <mesh geometry={nodes.Plane008.geometry} material={nodes.Plane008.material} position={[-30.811, 0.775, 21.942]} rotation={[Math.PI / 2, 0, 3.138]} scale={0.047} />
        <mesh geometry={nodes.Plane007.geometry} material={materials['Material.067']} position={[-24.895, 0.775, 18.877]} rotation={[Math.PI / 2, 0, -1.574]} scale={0.047} />
        <mesh geometry={nodes.Plane006.geometry} material={nodes.Plane006.material} position={[-30.789, 0.775, 15.854]} rotation={[Math.PI / 2, 0, 3.138]} scale={0.047} />
        <mesh geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[-33.808, 0.775, 18.905]} rotation={[Math.PI / 2, 0, -1.574]} scale={0.047} />
        <mesh geometry={nodes.Plane004.geometry} material={materials['Material.068']} position={[-29.242, 0.4, 18.919]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={0.047} />
        <mesh geometry={nodes.Cube066.geometry} material={nodes.Cube066.material} position={[-28.551, 1.272, 21.897]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={[0.025, 0.823, 0.025]} />
        <mesh geometry={nodes.Cube065.geometry} material={materials['Material.069']} position={[-26.533, 1.272, 21.89]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={[0.025, 0.823, 0.025]} />
        <mesh geometry={nodes.Cube058.geometry} material={nodes.Cube058.material} position={[-32.025, 1.272, 15.894]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={[0.025, 0.823, 0.025]} />
        <mesh geometry={nodes.Cube055.geometry} material={nodes.Cube055.material} position={[-33.749, 0.306, 18.902]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={[3.306, 0.047, 0.115]} />
        <mesh geometry={nodes.Cube054.geometry} material={materials.LIGHT} position={[-26.731, 0.305, 21.464]} rotation={[0, -1.568, 0]} scale={0.035} />
        <mesh geometry={nodes.Cube053.geometry} material={materials.LIGHT} position={[-31.921, 0.305, 21.48]} rotation={[0, -1.568, 0]} scale={0.035} />
        <mesh geometry={nodes.Cube052.geometry} material={materials.LIGHT} position={[-31.868, 0.305, 16.084]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={0.035} />
        <mesh geometry={nodes.Cube050.geometry} material={materials.LIGHT} position={[-26.677, 0.305, 16.068]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={0.035} />
        <group position={[-25.487, 0.56, 20.444]} rotation={[Math.PI, -0.003, Math.PI]} scale={[0.141, 0.023, 0.646]}>
          <mesh geometry={nodes.Cube056.geometry} material={materials['Material.070']} />
          <mesh geometry={nodes.Cube056_1.geometry} material={materials['Material.071']} />
        </group>
        <group position={[-25.495, 0.56, 17.875]} rotation={[Math.PI, -0.003, Math.PI]} scale={[0.141, 0.023, 0.646]}>
          <mesh geometry={nodes.Cube055_1.geometry} material={materials['Material.070']} />
          <mesh geometry={nodes.Cube055_2.geometry} material={materials['Material.071']} />
        </group>
        <group position={[-31.193, 0.419, 21.362]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={[0.141, 0.023, 0.646]}>
          <mesh geometry={nodes.Cube054_1.geometry} material={materials['Material.070']} />
          <mesh geometry={nodes.Cube054_2.geometry} material={materials['Material.071']} />
        </group>
        <group position={[-27.651, 0.419, 21.351]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={[0.141, 0.023, 0.646]}>
          <mesh geometry={nodes.Cube053_1.geometry} material={materials['Material.070']} />
          <mesh geometry={nodes.Cube053_2.geometry} material={materials['Material.071']} />
        </group>
        <group position={[-32.977, 0.419, 20.467]} rotation={[Math.PI, -0.003, Math.PI]} scale={[0.141, 0.023, 0.646]}>
          <mesh geometry={nodes.Cube052_1.geometry} material={materials['Material.070']} />
          <mesh geometry={nodes.Cube052_2.geometry} material={materials['Material.071']} />
        </group>
        <group position={[-32.985, 0.419, 17.899]} rotation={[Math.PI, -0.003, Math.PI]} scale={[0.141, 0.023, 0.646]}>
          <mesh geometry={nodes.Cube051.geometry} material={materials['Material.070']} />
          <mesh geometry={nodes.Cube051_1.geometry} material={materials['Material.071']} />
        </group>
        <group position={[-31.208, 0.419, 16.314]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={[0.141, 0.023, 0.646]}>
          <mesh geometry={nodes.Cube050_1.geometry} material={materials['Material.070']} />
          <mesh geometry={nodes.Cube050_2.geometry} material={materials['Material.071']} />
        </group>
        <group position={[-27.667, 0.419, 16.303]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={[0.141, 0.023, 0.646]}>
          <mesh geometry={nodes.Cube048_1.geometry} material={materials['Material.070']} />
          <mesh geometry={nodes.Cube048_2.geometry} material={materials['Material.071']} />
        </group>
        <group position={[-32.389, 0.279, 18.923]} rotation={[0, -1.568, 0]} scale={0.055}>
          <mesh geometry={nodes.Cube078.geometry} material={materials['Material.072']} />
          <mesh geometry={nodes.Cube078_1.geometry} material={materials.LIGHT} />
          <mesh geometry={nodes.Cube078_2.geometry} material={materials['Material.073']} />
        </group>
        <group position={[-26.109, 0.279, 18.903]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={0.055}>
          <mesh geometry={nodes.Cube079.geometry} material={materials['Material.072']} />
          <mesh geometry={nodes.Cube079_1.geometry} material={materials.LIGHT} />
          <mesh geometry={nodes.Cube079_2.geometry} material={materials['Material.073']} />
        </group>
        <mesh geometry={nodes.Cube039.geometry} material={materials['Material.074']} position={[-30.239, 0.243, 18.903]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={[2.664, 0.029, 3.626]} />
        <group position={[-15.334, 0.072, -8.256]} scale={0.21}>
          <mesh geometry={nodes.Plane132.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Plane132_1.geometry} material={materials['Material.032']} />
        </group>
        <group position={[-13.582, 0.057, -9.212]} scale={0.21}>
          <mesh geometry={nodes.Plane133.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Plane133_1.geometry} material={materials['Material.032']} />
        </group>
        <group position={[-1.32, 0.047, -17.268]} scale={0.21}>
          <mesh geometry={nodes.Plane134.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Plane134_1.geometry} material={materials['Material.032']} />
        </group>
        <group position={[-0.029, 0.047, -18.615]} scale={0.21}>
          <mesh geometry={nodes.Plane135.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Plane135_1.geometry} material={materials['Material.032']} />
        </group>
        <group position={[-33.505, 0.069, -10.693]} scale={0.21}>
          <mesh geometry={nodes.Plane136.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Plane136_1.geometry} material={materials['Material.032']} />
        </group>
        <group position={[-43.371, -0.058, 10.3]} scale={0.21}>
          <mesh geometry={nodes.Plane137.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Plane137_1.geometry} material={materials['Material.032']} />
        </group>
        <group position={[-42.409, -0.058, 11.57]} scale={0.21}>
          <mesh geometry={nodes.Plane138.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Plane138_1.geometry} material={materials['Material.032']} />
        </group>
        <group position={[-34.439, 0.131, -6.548]} scale={0.21}>
          <mesh geometry={nodes.Plane139.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Plane139_1.geometry} material={materials['Material.032']} />
        </group>
        <group position={[-34.867, 0.073, 9.02]} scale={0.21}>
          <mesh geometry={nodes.Plane140.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Plane140_1.geometry} material={materials['Material.032']} />
        </group>
        <group position={[-14.973, 0.088, 5.628]} scale={0.21}>
          <mesh geometry={nodes.Plane141.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Plane141_1.geometry} material={materials['Material.032']} />
        </group>
        <group position={[-13.37, 0.1, 6.794]} scale={0.21}>
          <mesh geometry={nodes.Plane142.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Plane142_1.geometry} material={materials['Material.032']} />
        </group>
        <group position={[-22.732, 0.073, 11.178]} scale={0.21}>
          <mesh geometry={nodes.Plane143.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Plane143_1.geometry} material={materials['Material.032']} />
        </group>
        <group position={[-23.912, 0.078, -12.432]} scale={0.21}>
          <mesh geometry={nodes.Plane144.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Plane144_1.geometry} material={materials['Material.032']} />
        </group>
        <group position={[-8.406, 0.066, -6.364]} scale={0.21}>
          <mesh geometry={nodes.Plane145.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Plane145_1.geometry} material={materials['Material.032']} />
        </group>
        <group position={[-8.073, 0.019, 4.816]} scale={0.21}>
          <mesh geometry={nodes.Plane146.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Plane146_1.geometry} material={materials['Material.032']} />
        </group>
        <group position={[-30.652, 0.507, -20.66]} rotation={[Math.PI, -1.554, Math.PI]} scale={0.399}>
          <mesh geometry={nodes.FootballBall_1.geometry} material={materials.White} />
          <mesh geometry={nodes.FootballBall_2.geometry} material={materials.Black} />
        </group>
        <mesh
          onPointerEnter={(e) => setText('TelePort')}
          onPointerLeave={(e) => clear()} geometry={nodes.Sphere_019_Sphere_002_0006.geometry} material={materials['build_mat.003']} position={[-43.654, 1.137, -8.149]} rotation={[0, 1.467, 0]} scale={0.158} />
        <mesh
          onPointerEnter={(e) => setText('TelePort')}
          onPointerLeave={(e) => clear()} geometry={nodes.Sphere_019_Sphere_002_0007.geometry} material={materials['build_mat.003']} position={[-43.654, 1.137, -8.149]} rotation={[0, 1.467, 0]} scale={0.158} />
        <mesh
          onPointerEnter={(e) => setText('TelePort')}
          onPointerLeave={(e) => clear()} geometry={nodes.Sphere_019_Sphere_002_0008.geometry} material={materials['build_mat.003']} position={[-43.654, 1.137, -8.149]} rotation={[0, 1.467, 0]} scale={0.158} />
        <mesh geometry={nodes.Object_10008.geometry} material={materials['Trek_Material_free.001']} position={[-11.546, 0.194, 13.432]} rotation={[-Math.PI, 1.548, -Math.PI]} scale={0.189} />
        <mesh geometry={nodes.Plane.geometry} material={materials['Material.003']} position={[-22.376, 0.811, 8.504]} rotation={[-Math.PI / 2, 0, -0.463]} scale={[0.431, 0.404, 0.395]} />
        <mesh geometry={nodes.Plane047.geometry} material={materials['Material.003']} position={[-23.265, 0.811, 8.064]} rotation={[-Math.PI / 2, 0, -0.463]} scale={[0.431, 0.404, 0.395]} />
        <mesh geometry={nodes.Plane048.geometry} material={materials['Material.003']} position={[-21.586, 0.808, 8.901]} rotation={[-Math.PI / 2, 0, -0.463]} scale={[0.336, 0.384, 0.395]} />
        <mesh geometry={nodes.Plane049.geometry} material={materials['Material.003']} position={[-21.586, 1.872, 8.901]} rotation={[-Math.PI / 2, 0, -0.463]} scale={[0.336, 0.384, 0.395]} />
        <mesh geometry={nodes.Plane050.geometry} material={materials['Material.003']} position={[-22.376, 1.867, 8.504]} rotation={[-Math.PI / 2, 0, -0.463]} scale={[0.431, 0.404, 0.395]} />
        <mesh geometry={nodes.Plane051.geometry} material={materials['Material.003']} position={[-23.265, 1.873, 8.064]} rotation={[-Math.PI / 2, 0, -0.463]} scale={[0.431, 0.404, 0.395]} />
        <mesh geometry={nodes.Plane052.geometry} material={materials['Material.003']} position={[-23.507, 1.882, 7.286]} rotation={[-Math.PI / 2, 0, -2.004]} scale={[0.431, 0.404, 0.395]} />
        <mesh geometry={nodes.Plane053.geometry} material={materials['Material.003']} position={[-23.065, 1.893, 6.383]} rotation={[-Math.PI / 2, 0, -2.004]} scale={[0.45, 0.463, 0.395]} />
        <mesh geometry={nodes.Plane054.geometry} material={materials['Material.003']} position={[-23.072, 0.818, 6.368]} rotation={[-Math.PI / 2, 0, -2.004]} scale={[0.45, 0.463, 0.395]} />
        <mesh geometry={nodes.Plane055.geometry} material={materials['Material.003']} position={[-23.53, 0.807, 7.288]} rotation={[-Math.PI / 2, 0, -2.004]} scale={[0.431, 0.404, 0.395]} />
        <mesh geometry={nodes.Plane056.geometry} material={materials['Material.003']} position={[-22.177, 0.811, -9.887]} rotation={[Math.PI / 2, 0, 2.678]} scale={[-0.431, -0.404, -0.395]} />
        <mesh geometry={nodes.Plane057.geometry} material={materials['Material.003']} position={[-23.066, 0.811, -9.448]} rotation={[Math.PI / 2, 0, 2.678]} scale={[-0.431, -0.404, -0.395]} />
        <mesh geometry={nodes.Plane058.geometry} material={materials['Material.003']} position={[-21.387, 0.808, -10.284]} rotation={[Math.PI / 2, 0, 2.678]} scale={[-0.336, -0.384, -0.395]} />
        <mesh geometry={nodes.Plane059.geometry} material={materials['Material.003']} position={[-21.387, 1.872, -10.284]} rotation={[Math.PI / 2, 0, 2.678]} scale={[-0.336, -0.384, -0.395]} />
        <mesh geometry={nodes.Plane060.geometry} material={materials['Material.003']} position={[-22.177, 1.867, -9.887]} rotation={[Math.PI / 2, 0, 2.678]} scale={[-0.431, -0.404, -0.395]} />
        <mesh geometry={nodes.Plane061.geometry} material={materials['Material.003']} position={[-23.066, 1.873, -9.448]} rotation={[Math.PI / 2, 0, 2.678]} scale={[-0.431, -0.404, -0.395]} />
        <mesh geometry={nodes.Plane062.geometry} material={materials['Material.003']} position={[-23.308, 1.882, -8.67]} rotation={[Math.PI / 2, 0, 1.137]} scale={[-0.431, -0.404, -0.395]} />
        <mesh geometry={nodes.Plane063.geometry} material={materials['Material.003']} position={[-22.866, 1.893, -7.767]} rotation={[Math.PI / 2, 0, 1.137]} scale={[-0.45, -0.463, -0.395]} />
        <mesh geometry={nodes.Plane064.geometry} material={materials['Material.003']} position={[-22.873, 0.818, -7.752]} rotation={[Math.PI / 2, 0, 1.137]} scale={[-0.45, -0.463, -0.395]} />
        <mesh geometry={nodes.Plane065.geometry} material={materials['Material.003']} position={[-23.319, 0.789, -8.669]} rotation={[Math.PI / 2, 0, 1.137]} scale={[-0.431, -0.404, -0.395]} />
        <mesh geometry={nodes.Plane067.geometry} material={materials['Material.003']} position={[-27.003, 0.811, -9.543]} rotation={[-Math.PI / 2, 0, 2.678]} scale={[0.431, 0.404, 0.395]} />
        <mesh geometry={nodes.Plane069.geometry} material={materials['Material.003']} position={[-28.957, 1.872, -10.517]} rotation={[-Math.PI / 2, 0, 2.678]} scale={[0.49, 0.435, 0.395]} />
        <mesh geometry={nodes.Plane070.geometry} material={materials['Material.003']} position={[-27.974, 1.867, -10.006]} rotation={[-Math.PI / 2, 0, 2.678]} scale={[0.478, 0.416, 0.395]} />
        <mesh geometry={nodes.Plane071.geometry} material={materials['Material.003']} position={[-27.003, 1.873, -9.543]} rotation={[-Math.PI / 2, 0, 2.678]} scale={[0.431, 0.404, 0.395]} />
        <mesh geometry={nodes.Plane072.geometry} material={materials['Material.003']} position={[-26.76, 1.882, -8.765]} rotation={[-Math.PI / 2, 0, 1.137]} scale={[0.431, 0.404, 0.395]} />
        <mesh geometry={nodes.Plane073.geometry} material={materials['Material.003']} position={[-27.202, 1.893, -7.862]} rotation={[-Math.PI / 2, 0, 1.137]} scale={[0.45, 0.463, 0.395]} />
        <mesh geometry={nodes.Plane074.geometry} material={materials['Material.003']} position={[-27.195, 0.818, -7.847]} rotation={[-Math.PI / 2, 0, 1.137]} scale={[0.45, 0.463, 0.395]} />
        <mesh geometry={nodes.Plane075.geometry} material={materials['Material.003']} position={[-26.75, 0.789, -8.764]} rotation={[-Math.PI / 2, 0, 1.137]} scale={[0.431, 0.404, 0.395]} />
        <mesh geometry={nodes.Plane068.geometry} material={materials['Material.003']} position={[-28.957, 0.786, -10.517]} rotation={[-Math.PI / 2, 0, 2.678]} scale={[0.49, 0.435, 0.395]} />
        <mesh geometry={nodes.Plane066.geometry} material={materials['Material.003']} position={[-27.974, 0.796, -10.006]} rotation={[-Math.PI / 2, 0, 2.678]} scale={[0.478, 0.416, 0.395]} />
        <mesh geometry={nodes.Plane077.geometry} material={materials['Material.003']} position={[-27.217, 0.811, 8.113]} rotation={[Math.PI / 2, 0, -0.463]} scale={[-0.431, -0.404, -0.395]} />
        <mesh geometry={nodes.Plane079.geometry} material={materials['Material.003']} position={[-29.178, 1.872, 9.058]} rotation={[Math.PI / 2, 0, -0.463]} scale={[-0.485, -0.446, -0.395]} />
        <mesh geometry={nodes.Plane080.geometry} material={materials['Material.003']} position={[-28.184, 1.867, 8.589]} rotation={[Math.PI / 2, 0, -0.463]} scale={[-0.474, -0.415, -0.395]} />
        <mesh geometry={nodes.Plane081.geometry} material={materials['Material.003']} position={[-27.217, 1.873, 8.113]} rotation={[Math.PI / 2, 0, -0.463]} scale={[-0.431, -0.404, -0.395]} />
        <mesh geometry={nodes.Plane082.geometry} material={materials['Material.003']} position={[-26.971, 1.882, 7.38]} rotation={[Math.PI / 2, 0, -2.004]} scale={[-0.465, -0.411, -0.395]} />
        <mesh geometry={nodes.Plane083.geometry} material={materials['Material.003']} position={[-27.416, 1.893, 6.432]} rotation={[Math.PI / 2, 0, -2.004]} scale={[-0.45, -0.463, -0.395]} />
        <mesh geometry={nodes.Plane084.geometry} material={materials['Material.003']} position={[-27.409, 0.818, 6.417]} rotation={[Math.PI / 2, 0, -2.004]} scale={[-0.45, -0.463, -0.395]} />
        <mesh geometry={nodes.Plane085.geometry} material={materials['Material.003']} position={[-26.971, 0.808, 7.38]} rotation={[Math.PI / 2, 0, -2.004]} scale={[-0.465, -0.411, -0.395]} />
        <mesh geometry={nodes.Plane076.geometry} material={materials['Material.003']} position={[-28.184, 0.794, 8.589]} rotation={[Math.PI / 2, 0, -0.463]} scale={[-0.474, -0.415, -0.395]} />
        <mesh geometry={nodes.Plane078.geometry} material={materials['Material.003']} position={[-29.178, 0.808, 9.058]} rotation={[Math.PI / 2, 0, -0.463]} scale={[-0.485, -0.446, -0.395]} />
        <mesh geometry={nodes.Text.geometry} material={materials['Material.004']} position={[-18.021, 1.69, 0.322]} rotation={[1.571, 0.019, -1.57]} scale={0.588} />
        <mesh geometry={nodes.Plane086.geometry} material={materials['Material.003']} position={[-21.056, 1.922, 10.974]} rotation={[-Math.PI / 2, 0, 2.693]} scale={[0.219, 0.207, 0.157]} />
        <mesh geometry={nodes.Plane087.geometry} material={materials['Material.003']} position={[-21.056, 0.87, 10.974]} rotation={[-Math.PI / 2, 0, 2.693]} scale={[0.219, 0.207, 0.157]} />
        <mesh geometry={nodes.Plane090.geometry} material={materials['Material.003']} position={[-23.421, 0.873, 9.884]} rotation={[-Math.PI / 2, 0, 2.693]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane091.geometry} material={materials['Material.003']} position={[-23.421, 1.921, 9.884]} rotation={[-Math.PI / 2, 0, 2.693]} scale={[0.219, 0.207, 0.157]} />
        <mesh geometry={nodes.Plane089.geometry} material={materials['Material.003']} position={[-22.187, 0.873, 10.453]} rotation={[-Math.PI / 2, 0, 2.693]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane088.geometry} material={materials['Material.003']} position={[-22.182, 1.918, 10.444]} rotation={[-Math.PI / 2, 0, 2.693]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane092.geometry} material={materials['Material.003']} position={[-24.607, 0.873, 9.306]} rotation={[-Math.PI / 2, 0, 2.693]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane093.geometry} material={materials['Material.003']} position={[-24.607, 1.927, 9.306]} rotation={[-Math.PI / 2, 0, 2.693]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane094.geometry} material={materials['Material.003']} position={[-25.812, 1.927, 9.255]} rotation={[-Math.PI / 2, 0, -2.704]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane095.geometry} material={materials['Material.003']} position={[-26.984, 1.927, 9.828]} rotation={[-Math.PI / 2, 0, -2.704]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane096.geometry} material={materials['Material.003']} position={[-28.165, 1.927, 10.372]} rotation={[-Math.PI / 2, 0, -2.704]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane097.geometry} material={materials['Material.003']} position={[-29.371, 1.927, 10.957]} rotation={[-Math.PI / 2, 0, -2.704]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane098.geometry} material={materials['Material.003']} position={[-25.812, 0.871, 9.255]} rotation={[-Math.PI / 2, 0, -2.704]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane099.geometry} material={materials['Material.003']} position={[-26.984, 0.871, 9.828]} rotation={[-Math.PI / 2, 0, -2.704]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane100.geometry} material={materials['Material.003']} position={[-28.165, 0.871, 10.372]} rotation={[-Math.PI / 2, 0, -2.704]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane101.geometry} material={materials['Material.003']} position={[-29.371, 0.871, 10.957]} rotation={[-Math.PI / 2, 0, -2.704]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane102.geometry} material={materials['Material.003']} position={[-20.839, 1.927, -12.337]} rotation={[-Math.PI / 2, 0, 0.436]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane103.geometry} material={materials['Material.003']} position={[-21.956, 1.927, -11.82]} rotation={[-Math.PI / 2, 0, 0.436]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane104.geometry} material={materials['Material.003']} position={[-23.16, 1.927, -11.262]} rotation={[-Math.PI / 2, 0, 0.436]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane105.geometry} material={materials['Material.003']} position={[-24.383, 1.927, -10.706]} rotation={[-Math.PI / 2, 0, 0.436]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane106.geometry} material={materials['Material.003']} position={[-20.839, 0.861, -12.337]} rotation={[-Math.PI / 2, 0, 0.436]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane107.geometry} material={materials['Material.003']} position={[-21.956, 0.861, -11.82]} rotation={[-Math.PI / 2, 0, 0.436]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane108.geometry} material={materials['Material.003']} position={[-23.16, 0.861, -11.262]} rotation={[-Math.PI / 2, 0, 0.436]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane109.geometry} material={materials['Material.003']} position={[-24.383, 0.861, -10.706]} rotation={[-Math.PI / 2, 0, 0.436]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane110.geometry} material={materials['Material.003']} position={[-25.579, 0.871, -10.658]} rotation={[-Math.PI / 2, 0, -0.456]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane111.geometry} material={materials['Material.003']} position={[-25.579, 1.93, -10.658]} rotation={[-Math.PI / 2, 0, -0.456]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane112.geometry} material={materials['Material.003']} position={[-26.755, 1.93, -11.23]} rotation={[-Math.PI / 2, 0, -0.456]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane113.geometry} material={materials['Material.003']} position={[-26.755, 0.859, -11.23]} rotation={[-Math.PI / 2, 0, -0.456]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane114.geometry} material={materials['Material.003']} position={[-27.924, 0.859, -11.8]} rotation={[-Math.PI / 2, 0, -0.456]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane115.geometry} material={materials['Material.003']} position={[-27.924, 1.924, -11.8]} rotation={[-Math.PI / 2, 0, -0.456]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane116.geometry} material={materials['Material.003']} position={[-29.092, 1.924, -12.366]} rotation={[-Math.PI / 2, 0, -0.456]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane117.geometry} material={materials['Material.003']} position={[-29.092, 0.864, -12.366]} rotation={[-Math.PI / 2, 0, -0.456]} scale={[0.243, 0.212, 0.149]} />
        <mesh geometry={nodes.Plane118.geometry} material={materials['Material.008']} position={[-16.192, 4.823, -1.273]} rotation={[1.571, 0.006, -1.575]} scale={[0.55, 0.55, 0.35]} />
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.074']} position={[-30.239, 0.243, 15.725]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={[2.664, 0.029, 3.626]} />
        <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[-24.885, 0.306, 18.946]} rotation={[Math.PI, -1.566, Math.PI]} scale={[3.306, 0.047, 0.115]} />
        <group position={[-32.555, 0.398, 6.562]} rotation={[Math.PI, -0.458, Math.PI]} scale={[0.255, 0.042, 1.175]}>
          <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.070']} />
          <mesh geometry={nodes.Cube004_2.geometry} material={materials['Material.071']} />
        </group>
        <group position={[-33.405, 0.398, 6.985]} rotation={[Math.PI, -0.458, Math.PI]} scale={[0.255, 0.042, 1.175]}>
          <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.070']} />
          <mesh geometry={nodes.Cube005_2.geometry} material={materials['Material.071']} />
        </group>
        <mesh geometry={nodes.Object_14005.geometry} material={materials.Trek_Material_free} position={[5.454, 0.21, -0.087]} rotation={[3.138, -0.013, 3.141]} scale={[0.932, 0.189, 3.529]} />
        <Float
          speed={3} // Animation speed, defaults to 1
          rotationIntensity={0} // XYZ rotation intensity, defaults to 1
          floatIntensity={1} // Up/down float intensity, works like a multiplier with floatingRange,defaults to 1
          floatingRange={[0, 0.3]} >

          {/* <RigidBody type="fixed" sensor onIntersectionEnter={()=>{console.log("jkn"); window.location.href = '/SolarSystem?gravity=0&flycontrol=true';}}></RigidBody> */}



          {/* change the url to that specific component */}
          <RigidBody type="fixed" sensor onIntersectionEnter={() => { console.log("jkn"); window.location.href = '/CorridorChemistry'; }}>
            <mesh geometry={nodes.Torus004.geometry} material={materials['Material.006']} position={[-13.692, 0.2, -17.137]} scale={0.66} />
          </RigidBody>
          <RigidBody type="fixed" sensor onIntersectionEnter={() => { console.log("jkn"); window.location.href = '/CorridorAstronomy'; }}>
            <mesh geometry={nodes.Torus001.geometry} material={materials['Material.006']} position={[-40.155, 0.314, -13.305]} scale={0.66} />
          </RigidBody>

          <mesh geometry={nodes.Torus002.geometry} material={materials['Material.006']} position={[-42.263, 0.314, -7.224]} scale={0.66} />

          <RigidBody type="fixed" sensor onIntersectionEnter={() => { console.log("jkn"); window.location.href = 'https://edu-verse-chat.vercel.app/'; }}>
            <mesh geometry={nodes.Torus003.geometry} material={materials['Material.006']} position={[1.5, 0.314, 0]} scale={[0.4, 4, 3]} />
          </RigidBody>

          <RigidBody type="fixed" sensor onIntersectionEnter={() => { console.log("jkn"); window.location.href = '/CorridorBiology'; }}>
            <mesh geometry={nodes.Torus005.geometry} material={materials['Material.006']} position={[-13.652, 0.314, 15.75]} scale={0.66} />
          </RigidBody>

          <mesh geometry={nodes.Torus006.geometry} material={materials['Material.006']} position={[-7.469, 0.314, 6.358]} scale={0.66} />

          <RigidBody type="fixed" sensor onIntersectionEnter={() => { console.log("jkn"); window.location.href = 'https://edu-verse-chat.vercel.app/chats'; }}>
            <mesh geometry={nodes.Torus007.geometry} material={materials['Material.006']} position={[-14.907, 0.318, -0.749]} scale={0.452} />
          </RigidBody>

          <mesh geometry={nodes.Torus008.geometry} material={materials['Material.006']} position={[-6.256, 0.314, 14.896]} scale={0.66} />

          <RigidBody type="fixed" sensor onIntersectionEnter={()=>{console.log("jkn"); window.location.href = 'https://www.google.com/';}}>
          <mesh geometry={nodes.Torus009.geometry} material={materials['Material.006']} position={[-7.076, 0.314, -15.688]} scale={0.66} />
          </RigidBody>
        </Float>
        <mesh geometry={nodes.Text001.geometry} material={materials['Material.009']} position={[-8.08, 2.155, -16.434]} rotation={[1.558, 0, 0]} scale={0.352} />
        <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[5.197, 0.037, 0.076]} rotation={[1.568, Math.PI / 2, 0]} scale={[0.07, 12.433, 1.299]} />
        <mesh geometry={nodes.Torus_013_Torus_001_2001.geometry} material={materials['floor.002']} position={[-51.007, -155.513, 101.189]} rotation={[Math.PI / 2, 1.555, 0]} />

      </group>
    </RigidBody>
  )
}

useGLTF.preload('/campus.glb')
