/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 chemLabFinal.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { useSharedState } from './sharedState';
import { PresentationControls } from '@react-three/drei';


export function ChemLabFinal(props) {
  const { setText, setDesc } = useSharedState();

  function clear() {
    setText('');
    setDesc('');
  }
  function scopeClick() {
    setDesc("A chemistry lab microscope is a specialized optical instrument used in laboratories for detailed examination of chemical samples at the microscopic level. It aids scientists in analyzing the composition, structure, and behavior of various substances, facilitating research in fields like organic and inorganic chemistry, materials science, and chemical engineering.");
  }
  function distillationClick() {
    setDesc("A chemistry lab distillation apparatus is a precise equipment set used to separate components of a liquid mixture based on their boiling points. It typically consists of a boiling flask, condenser, and collection flask. By heating the mixture, vaporizing the component with the lower boiling point, and condensing it back into a liquid, scientists can isolate and purify substances for various chemical analyses and experiments.");
  }
  function burnerClick() {
    setDesc("A Bunsen burner is a common laboratory tool used for heating, sterilizing, and combustion in chemistry experiments. It consists of a metal tube connected to a gas source, allowing precise control of the flame's size and intensity. Scientists use it for tasks like heating chemicals and conducting experiments that require a consistent heat source in the laboratory setting.");
  }
  const { nodes, materials } = useGLTF('/chemLabFinal.glb')
  return (
    <RigidBody type='fixed' >
    <group {...props} dispose={null} position={[-450, -10, -50]} scale={[4,2,4]}>
      <group position={[96.696, -0.174, 0.056]} rotation={[-Math.PI / 2, 0, 0]} scale={[108.926, 76.243, 81.969]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[14.777, 5.017, 7.41]} scale={6.501}>
            <mesh geometry={nodes.pCube47_lambert1_0.geometry} material={materials.lambert1} position={[0.331, -0.326, 0.666]} scale={[0.036, 0.869, 0.036]} />
            <mesh geometry={nodes.pCube48_lambert1_0.geometry} material={materials.lambert1} position={[0.331, -0.326, -0.703]} scale={[0.036, 0.869, 0.036]} />
            <mesh geometry={nodes.pCube49_lambert1_0.geometry} material={materials.lambert1} position={[0.331, 0.086, -0.016]} rotation={[Math.PI / 2, 0, 0]} scale={[0.036, 1.333, 0.036]} />
            <mesh geometry={nodes.pCube50_lambert1_0.geometry} material={materials.lambert1} position={[-0.245, -0.326, 0.666]} scale={[0.036, 0.869, 0.036]} />
            <mesh geometry={nodes.pCube51_lambert1_0.geometry} material={materials.lambert1} position={[-0.245, -0.326, -0.703]} scale={[0.036, 0.869, 0.036]} />
            <mesh geometry={nodes.pCube52_lambert1_0.geometry} material={materials.lambert1} position={[0.038, 0.086, 0.666]} rotation={[0, 0, -Math.PI / 2]} scale={[0.036, 0.598, 0.036]} />
            <mesh geometry={nodes.pCube53_lambert1_0.geometry} material={materials.lambert1} position={[0.038, 0.086, -0.703]} rotation={[0, 0, -Math.PI / 2]} scale={[0.036, 0.598, 0.036]} />
            <mesh geometry={nodes.pCube54_lambert1_0.geometry} material={materials.lambert1} position={[0.038, -0.744, 0.666]} rotation={[0, 0, -Math.PI / 2]} scale={[0.036, 0.598, 0.036]} />
            <mesh geometry={nodes.pCube55_lambert1_0.geometry} material={materials.lambert1} position={[0.038, -0.744, -0.703]} rotation={[0, 0, -Math.PI / 2]} scale={[0.036, 0.598, 0.036]} />
            <mesh geometry={nodes.pCube56_lambert1_0.geometry} material={materials.lambert1} position={[0.331, -0.743, -0.016]} rotation={[Math.PI / 2, 0, 0]} scale={[0.036, 1.333, 0.036]} />
            <mesh geometry={nodes.pCube58_lambert1_0.geometry} material={materials.lambert1} position={[0.034, 0.117, -0.02]} scale={[0.632, 0.019, 1.4]} />
            <mesh geometry={nodes.pCube59_lambert1_0.geometry} material={materials.lambert1} position={[0.351, -0.312, -0.02]} rotation={[0, 0, -Math.PI / 2]} scale={[0.863, 0.009, 1.4]} />
            <mesh geometry={nodes.pCube61_lambert1_0.geometry} material={materials.lambert1} position={[-0.246, 0.086, -0.016]} rotation={[Math.PI / 2, 0, 0]} scale={[0.036, 1.333, 0.036]} />
            <mesh geometry={nodes.pCylinder141_lambert1_0.geometry} material={materials.lambert1} position={[-2.198, -0.772, -3.23]} scale={0.154} />
            <mesh geometry={nodes.polySurface283_lambert1_0.geometry} material={materials.lambert1} position={[-0.063, -0.391, 0.498]} scale={[0.725, 0.725, 0.284]} />
            <mesh geometry={nodes.polySurface284_lambert1_0.geometry} material={materials.lambert1} position={[-0.064, -0.365, 0.498]} scale={[0.725, 0.68, 0.272]} />
            <mesh geometry={nodes.polySurface285_lambert1_0.geometry} material={materials.lambert1} position={[-0.064, -0.514, 0.498]} scale={[0.725, 0.68, 0.272]} />
            <mesh geometry={nodes.polySurface286_lambert1_0.geometry} material={materials.lambert1} position={[-0.064, -0.663, 0.498]} scale={[0.725, 0.68, 0.272]} />
            <mesh geometry={nodes.polySurface287_lambert1_0.geometry} material={materials.lambert1} position={[-0.064, -0.812, 0.498]} scale={[0.725, 0.68, 0.272]} />
            <mesh geometry={nodes.polySurface288_lambert1_0.geometry} material={materials.lambert1} position={[-0.064, -0.961, 0.498]} scale={[0.725, 0.68, 0.272]} />
            <mesh geometry={nodes.polySurface478_lambert1_0.geometry} material={materials.lambert1} position={[0.438, -0.581, -0.003]} rotation={[0, -1.571, 0]} scale={0.111} />
            <mesh geometry={nodes.polySurface479_lambert1_0.geometry} material={materials.lambert1} position={[0.438, -0.74, -0.003]} rotation={[0, -1.571, 0]} scale={0.111} />
            <mesh geometry={nodes.polySurface480_lambert1_0.geometry} material={materials.lambert1} position={[0.438, -0.89, -0.003]} rotation={[0, -1.571, 0]} scale={0.111} />
            <mesh geometry={nodes.polySurface481_lambert1_0.geometry} material={materials.lambert1} position={[0.438, -1.035, -0.003]} rotation={[0, -1.571, 0]} scale={0.111} />
            <mesh geometry={nodes.polySurface482_lambert1_0.geometry} material={materials.lambert1} position={[0.438, -1.19, -0.003]} rotation={[0, -1.571, 0]} scale={0.111} />
          </group>
          <group position={[0.585, 0, 6.465]} scale={9.768}>
            <group position={[-0.016, 0.996, 0.297]} scale={0.035}>
              <mesh geometry={nodes.pasted__polySurface17_pasted__blinn1_0.geometry} material={materials.pasted__blinn1} />
              <mesh geometry={nodes.pasted__polySurface17_pasted__blinn2_0.geometry} material={materials.pasted__blinn2} />
            </group>
            <group position={[0.157, 0, -0.828]} rotation={[0, -0.305, 0]} scale={0.102}>
              <mesh geometry={nodes.polySurface561_blinn3_0.geometry} material={materials.blinn3} />
              <mesh geometry={nodes.polySurface561_lambert1_0.geometry} material={materials.lambert1} />
            </group>
            <mesh geometry={nodes.pCylinder119_blinn3_0.geometry} material={materials.blinn3} position={[-0.002, 1.154, -0.36]} scale={0.055} />
            <mesh geometry={nodes.pCylinder120_blinn3_0.geometry} material={materials.blinn3} position={[-0.002, 1.153, -0.297]} scale={0.055} />
            <mesh geometry={nodes.pCylinder121_blinn3_0.geometry} material={materials.blinn3} position={[-0.002, 1.153, -0.234]} scale={0.055} />
            <mesh geometry={nodes.pCylinder122_blinn3_0.geometry} material={materials.blinn3} position={[-0.002, 1.153, -0.171]} scale={0.055} />
            <mesh geometry={nodes.pCylinder133_blinn3_0.geometry} material={materials.blinn3} position={[0.007, 1.064, 0.347]} rotation={[-2.078, 0, 0]} scale={0.055} />
            <mesh geometry={nodes.pCylinder134_blinn3_0.geometry} material={materials.blinn3} position={[-0.083, 1.064, 0.347]} rotation={[-2.078, 0, 0.147]} scale={0.055} />
            <mesh geometry={nodes.pCylinder135_blinn3_0.geometry} material={materials.blinn3} position={[-0.031, 0.924, 0.329]} rotation={[-2.086, 0, 0.077]} scale={0.033} />
            <mesh geometry={nodes.pCylinder136_blinn3_0.geometry} material={materials.blinn3} position={[-0.1, 0.98, 0.329]} rotation={[-2.086, 0, -0.037]} scale={0.033} />
            <mesh geometry={nodes.pCylinder148_blinn3_0.geometry} material={materials.blinn3} position={[0.031, 0.874, -0.321]} rotation={[0, 0.281, 0]} scale={0.022} />
            <mesh geometry={nodes.pCylinder197_blinn3_0.geometry} material={materials.blinn3} position={[-0.002, 0.506, 1.779]} scale={0.055} />
            <mesh geometry={nodes.pCylinder198_blinn3_0.geometry} material={materials.blinn3} position={[0.08, 0.506, 1.779]} scale={0.055} />
            <mesh geometry={nodes.pCylinder199_blinn3_0.geometry} material={materials.blinn3} position={[0.633, 0.506, 1.779]} scale={0.055} />
            <mesh geometry={nodes.pCylinder200_blinn3_0.geometry} material={materials.blinn3} position={[-0.208, 0.487, 1.769]} scale={0.033} />
            <mesh geometry={nodes.pCylinder201_blinn3_0.geometry} material={materials.blinn3} position={[0.046, 0.487, 1.861]} scale={0.033} />
            <mesh geometry={nodes.pCylinder202_blinn3_0.geometry} material={materials.blinn3} position={[0.402, 0.487, 1.756]} scale={0.033} />
            <mesh geometry={nodes.pCylinder203_blinn3_0.geometry} material={materials.blinn3} position={[0.361, 0.487, 1.756]} scale={0.033} />
            <mesh geometry={nodes.pCylinder22_blinn3_0.geometry} material={materials.blinn3} position={[-0.002, 0.901, -0.36]} scale={0.055} />
            <mesh geometry={nodes.pCylinder75_blinn3_0.geometry} material={materials.blinn3} position={[-0.027, 0.882, -0.166]} scale={0.033} />
            <mesh geometry={nodes.pCylinder77_blinn3_0.geometry} material={materials.blinn3} position={[-0.004, 0.869, 0.131]} rotation={[0, 0.281, 0]} scale={0.017} />
            <mesh geometry={nodes.polySurface150_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface158_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface159_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface160_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface161_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface162_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface163_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface165_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface166_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface167_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface168_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface169_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface170_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface171_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface172_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface173_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface174_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface175_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface176_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface177_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface178_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface179_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface180_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface181_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface182_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface183_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface184_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface185_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface188_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface189_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface190_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface191_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface192_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface193_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface194_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface195_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface196_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface197_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface198_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface199_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface200_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface201_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface202_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface203_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface204_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface205_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface206_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface207_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface208_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface209_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface210_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface212_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface213_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface214_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface215_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface216_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface218_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface219_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface220_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface222_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface223_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface224_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface227_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface229_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface230_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface231_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface232_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface233_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface234_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface235_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface236_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface237_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface238_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface239_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface240_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface241_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface242_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface243_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface244_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface246_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface247_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface248_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface251_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, -0.806]} scale={0.102} />
            <mesh geometry={nodes.polySurface252_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface253_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface254_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface255_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface256_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface257_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface258_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface259_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface260_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface261_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface262_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface263_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface264_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface265_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface266_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface267_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface268_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface270_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface271_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface272_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface273_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface274_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface275_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface276_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface277_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface278_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface279_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface280_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface281_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface282_lambert1_0.geometry} material={materials.lambert1} position={[-0.406, 0, 0.003]} scale={0.102} />
            <mesh geometry={nodes.polySurface645_blinn3_0.geometry} material={materials.blinn3} position={[2.348, 2.401, -0.081]} rotation={[-2.321, -Math.PI / 2, 0]} scale={0.102} />
            <mesh geometry={nodes.polySurface646_blinn3_0.geometry} material={materials.blinn3} position={[2.384, 2.401, -0.081]} rotation={[-2.321, -Math.PI / 2, 0]} scale={0.102} />
            <mesh geometry={nodes.polySurface647_blinn3_0.geometry} material={materials.blinn3} position={[2.419, 2.401, -0.081]} rotation={[-2.321, -Math.PI / 2, 0]} scale={0.102} />
            <mesh geometry={nodes.pSphere1_blinn3_0.geometry} material={materials.blinn3} position={[-0.045, 0.868, 0.16]} scale={0.019} />
            <mesh geometry={nodes.pSphere10_blinn3_0.geometry} material={materials.blinn3} position={[-0.147, 0.478, 1.798]} scale={0.028} />
            <mesh geometry={nodes.pSphere11_blinn3_0.geometry} material={materials.blinn3} position={[0.383, 0.478, 1.827]} scale={0.028} />
            <mesh geometry={nodes.pSphere12_blinn3_0.geometry} material={materials.blinn3} position={[0.585, 0.478, 1.832]} scale={0.028} />
            <mesh geometry={nodes.pSphere13_blinn3_0.geometry} material={materials.blinn3} position={[0.321, 0.478, 1.809]} scale={0.028} />
            <mesh geometry={nodes.pSphere14_blinn3_0.geometry} material={materials.blinn3} position={[-0.161, 0.478, 1.745]} scale={0.028} />
            <mesh geometry={nodes.pSphere3_blinn3_0.geometry} material={materials.blinn3} position={[-0.015, 1.141, 0.351]} rotation={[-2.227, 0, 0]} scale={0.019} />
            <mesh geometry={nodes.pSphere4_blinn3_0.geometry} material={materials.blinn3} position={[-0.004, 0.868, -0.423]} scale={0.019} />
            <mesh geometry={nodes.pSphere5_blinn3_0.geometry} material={materials.blinn3} position={[-0.023, 1.129, -0.095]} scale={0.028} />
            <mesh geometry={nodes.pSphere6_blinn3_0.geometry} material={materials.blinn3} position={[-0.023, 1.129, 0.021]} scale={0.028} />
            <mesh geometry={nodes.pSphere7_blinn3_0.geometry} material={materials.blinn3} position={[-0.045, 0.877, 0.021]} scale={0.028} />
          </group>
          <group position={[0.036, 4.322, -5.697]} scale={5.974}>
            <group position={[0.066, 0.905, -0.363]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.057}>
              <mesh geometry={nodes.pasted__polySurface18_pasted__blinn1_0.geometry} material={materials.pasted__blinn1} />
              <mesh geometry={nodes.pasted__polySurface18_pasted__blinn2_0.geometry} material={materials.pasted__blinn2} />
            </group>
            <group position={[0.108, -0.723, 0.718]} scale={0.167}>
              <mesh geometry={nodes.polySurface613_blinn3_0.geometry} material={materials.blinn3} />
              <mesh geometry={nodes.polySurface613_lambert1_0.geometry} material={materials.lambert1} />
            </group>
            <mesh geometry={nodes.pCylinder145_blinn3_0.geometry} material={materials.blinn3} position={[0.071, 0.719, -0.109]} scale={0.053} />
            <mesh geometry={nodes.pCylinder146_blinn3_0.geometry} material={materials.blinn3} position={[0.143, 0.715, 0.591]} rotation={[0, 0.281, 0]} scale={0.046} />
            <mesh geometry={nodes.pCylinder208_blinn3_0.geometry} material={materials.blinn3} position={[0.285, 0.325, 0.285]} rotation={[0, 0.281, 0]} scale={0.046} />
            <mesh geometry={nodes.pCylinder222_blinn3_0.geometry} material={materials.blinn3} position={[0.143, 0.326, 2.224]} rotation={[0, 0.281, 0]} scale={0.046} />
            <mesh geometry={nodes.polySurface149_lambert1_0.geometry} material={materials.lambert1} position={[-0.573, -0.723, 0.117]} rotation={[0, 0, -Math.PI]} scale={-0.167} />
            <mesh geometry={nodes.pSphere15_blinn3_0.geometry} material={materials.blinn3} position={[0.482, 0.309, 0.397]} scale={0.045} />
            <mesh geometry={nodes.pSphere16_blinn3_0.geometry} material={materials.blinn3} position={[0.339, 0.309, 0.598]} scale={0.045} />
            <mesh geometry={nodes.pSphere17_blinn3_0.geometry} material={materials.blinn3} position={[0.103, 0.312, 0.81]} scale={0.045} />
            <mesh geometry={nodes.pSphere18_blinn3_0.geometry} material={materials.blinn3} position={[0.103, 0.312, 1.909]} scale={0.045} />
            <mesh geometry={nodes.pSphere2_blinn3_0.geometry} material={materials.blinn3} position={[0.101, 0.309, 0.353]} scale={0.045} />
            <mesh geometry={nodes.pSphere8_blinn3_0.geometry} material={materials.blinn3} position={[-0.009, 0.71, 0.81]} scale={0.045} />
            <mesh geometry={nodes.pSphere9_blinn3_0.geometry} material={materials.blinn3} position={[-2.609, 0.295, 0.077]} scale={0.063} />
          </group>
          <group position={[0, 7.788, 24.373]} scale={5.699}>
            <group position={[0, -1.366, -4.277]} scale={0.175}>
              <mesh geometry={nodes.polySurface770_blinn2_0.geometry} material={materials.blinn2} />
              <mesh geometry={nodes.polySurface770_lambert1_0.geometry} material={materials.lambert1} />
            </group>
            <group position={[0, -1.366, -4.277]} rotation={[Math.PI, 0, 0]} scale={-0.175}>
              <mesh geometry={nodes.polySurface778_blinn2_0.geometry} material={materials.blinn2} />
              <mesh geometry={nodes.polySurface778_lambert1_0.geometry} material={materials.lambert1} />
            </group>
            <mesh geometry={nodes.pCube136_lambert1_0.geometry} material={materials.lambert1} position={[0, -0.991, 0.024]} scale={0.175} />
            <mesh geometry={nodes.pCube137_lambert1_0.geometry} material={materials.lambert1} position={[0, -0.591, 0.024]} scale={0.175} />
            <mesh geometry={nodes.pCube138_lambert1_0.geometry} material={materials.lambert1} position={[0, -0.188, 0.024]} scale={0.175} />
            <mesh geometry={nodes.pCube139_lambert1_0.geometry} material={materials.lambert1} position={[0, 0.205, 0.024]} scale={0.175} />
            <mesh geometry={nodes.polySurface768_lambert1_0.geometry} material={materials.lambert1} position={[0, -0.659, -0.019]} scale={0.175} />
          </group>
          <group position={[5.495, 7.788, 24.373]} scale={5.699}>
            <group position={[0, -1.366, -4.277]} scale={0.175}>
              <mesh geometry={nodes.polySurface770_blinn2_0001.geometry} material={materials.blinn2} />
              <mesh geometry={nodes.polySurface770_lambert1_0001.geometry} material={materials.lambert1} />
            </group>
            <group position={[0, -1.366, -4.277]} rotation={[Math.PI, 0, 0]} scale={-0.175}>
              <mesh geometry={nodes.polySurface778_blinn2_0001.geometry} material={materials.blinn2} />
              <mesh geometry={nodes.polySurface778_lambert1_0001.geometry} material={materials.lambert1} />
            </group>
            <mesh geometry={nodes.pCube136_lambert1_0001.geometry} material={materials.lambert1} position={[0, -0.991, 0.024]} scale={0.175} />
            <mesh geometry={nodes.pCube137_lambert1_0001.geometry} material={materials.lambert1} position={[0, -0.591, 0.024]} scale={0.175} />
            <mesh geometry={nodes.pCube138_lambert1_0001.geometry} material={materials.lambert1} position={[0, -0.188, 0.024]} scale={0.175} />
            <mesh geometry={nodes.pCube139_lambert1_0001.geometry} material={materials.lambert1} position={[0, 0.205, 0.024]} scale={0.175} />
            <mesh geometry={nodes.polySurface768_lambert1_0001.geometry} material={materials.lambert1} position={[0, -0.659, -0.019]} scale={0.175} />
          </group>
          <group position={[0, 0, 1.169]} rotation={[0, 0, -Math.PI]} scale={-1}>
            <mesh geometry={nodes.pCylinder175_lambert1_0001.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.pCylinder176_lambert1_0001.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.pCylinder177_lambert1_0001.geometry} material={materials.lambert1} />
          </group>
          <group position={[-1.933, -0.362, 5.062]} rotation={[0, 0.294, 0]}>
            <mesh geometry={nodes.polySurface788_lambert1_0.geometry} material={materials.lambert1} position={[-0.252, 0.008, 0.39]} rotation={[0, 0.026, 0]} />
            <mesh geometry={nodes.polySurface789_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[0.12, 10.975, -24.698]} scale={[0.417, 2.005, 0.417]}>
            <mesh geometry={nodes.polySurface637_lambert1_0.geometry} material={materials.lambert1} position={[0, 0, -1.354]} />
            <mesh geometry={nodes.polySurface638_lambert1_0.geometry} material={materials.lambert1} position={[4.904, -0.022, -1.354]} scale={[0.702, 1.035, 1.035]} />
            <mesh geometry={nodes.polySurface639_lambert1_0.geometry} material={materials.lambert1} position={[0.108, -0.022, -1.354]} scale={[0.702, 1.035, 1.035]} />
            <mesh geometry={nodes.polySurface641_lambert1_0.geometry} material={materials.lambert1} position={[15.713, -0.022, -1.354]} scale={[0.702, 1.035, 1.035]} />
            <mesh geometry={nodes.polySurface642_lambert1_0.geometry} material={materials.lambert1} position={[-8.467, -0.022, -1.354]} scale={[0.702, 1.035, 1.035]} />
          </group>
          <group position={[-1.036, -3.588, 26.602]} scale={1.24}>
            <mesh geometry={nodes.pCylinder181_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder181_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[4.729, -3.588, 26.602]} scale={1.24}>
            <mesh geometry={nodes.pCylinder187_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder187_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[-1.518, -3.839, 26.861]} scale={1.24}>
            <mesh geometry={nodes.pCylinder188_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder188_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[1.118, -3.839, 26.861]} scale={1.24}>
            <mesh geometry={nodes.pCylinder189_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder189_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[1.474, -3.839, 27.478]} scale={1.24}>
            <mesh geometry={nodes.pCylinder190_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder190_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[-1.683, -3.839, 27.464]} scale={1.24}>
            <mesh geometry={nodes.pCylinder191_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder191_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[4.071, -3.839, 27.464]} scale={1.24}>
            <mesh geometry={nodes.pCylinder192_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder192_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[7.138, -3.839, 26.918]} scale={1.24}>
            <mesh geometry={nodes.pCylinder193_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder193_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[6.535, -3.839, 26.618]} scale={1.24}>
            <mesh geometry={nodes.pCylinder194_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder194_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[6.669, -3.588, 27.492]} scale={1.24}>
            <mesh geometry={nodes.pCylinder195_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder195_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[6.006, -3.588, 27.109]} scale={1.24}>
            <mesh geometry={nodes.pCylinder196_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder196_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[0, -2.378, 0]}>
            <mesh geometry={nodes.pCylinder204_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder204_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[-0.608, -2.378, 0.344]}>
            <mesh geometry={nodes.pCylinder205_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder205_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[0.075, -2.378, 0.909]}>
            <mesh geometry={nodes.pCylinder206_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder206_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[-0.893, -2.378, 0.981]}>
            <mesh geometry={nodes.pCylinder207_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder207_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[-0.429, -4.643, 8.115]} scale={1.24}>
            <mesh geometry={nodes.pCylinder209_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder209_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[6.327, 0.199, -21.044]} rotation={[0, 1.571, 0]}>
            <mesh geometry={nodes.polySurface791_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface792_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface793_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface795_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[-3.171, 4.84, -8.297]}>
            <mesh geometry={nodes.pCylinder236_blinn3_0.geometry} material={materials.blinn3} />
            <mesh geometry={nodes.pCylinder236_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[0.595, 2.466, -0.952]}>
            <mesh geometry={nodes.pCylinder237_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.pCylinder237_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[0, 0, -0.565]}>
            <mesh geometry={nodes.polySurface147_blinn1_0.geometry} material={materials.blinn1} />
            <mesh geometry={nodes.polySurface147_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[0, 0, 5.316]}>
            <mesh geometry={nodes.polySurface634_blinn2_0.geometry} material={materials.blinn2} />
            <mesh geometry={nodes.polySurface634_blinn3_0.geometry} material={materials.blinn3} />
          </group>
          <group position={[4.271, -1.533, 26.572]}>
            <mesh geometry={nodes.polySurface783_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.polySurface783_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[1.697, -1.533, 26.454]}>
            <mesh geometry={nodes.polySurface784_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.polySurface784_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[3.793, -1.533, 26.454]}>
            <mesh geometry={nodes.polySurface785_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.polySurface785_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[-0.006, -0.01, 8.05]}>
            <mesh geometry={nodes.polySurface786_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.polySurface786_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[1.82, -2.378, 0]}>
            <mesh geometry={nodes.polySurface787_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.polySurface787_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[0.471, 2.454, 1.022]}>
            <mesh geometry={nodes.polySurface809_blinn4_0.geometry} material={materials.blinn4} />
            <mesh geometry={nodes.polySurface809_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group position={[0, 0, -23.619]} rotation={[0, -1.571, 0]}>
            <mesh geometry={nodes.pull_out_drobe_blinn1_0.geometry} material={materials.blinn1} />
            <mesh geometry={nodes.pull_out_drobe_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <mesh geometry={nodes.pCube145_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pCylinder166_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pCylinder167_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pCylinder169_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pCylinder170_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pCylinder171_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pCylinder172_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pCylinder173_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pCylinder174_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pCube118_lambert1_0.geometry} material={materials.lambert1} position={[0.101, -0.068, 0]} />
          <mesh geometry={nodes.pCube155_lambert1_0.geometry} material={materials.lambert1} position={[15.106, 1.43, 9.021]} />
          <mesh geometry={nodes.pCube82_lambert1_0.geometry} material={materials.lambert1} position={[0.143, 10.457, -25.298]} scale={[3.095, 0.606, 1.188]} />
          <mesh geometry={nodes.pCube83_lambert1_0.geometry} material={materials.lambert1} position={[5.952, 10.457, -25.298]} scale={[3.095, 0.606, 1.188]} />
          <mesh geometry={nodes.pCylinder131_lambert1_0.geometry} material={materials.lambert1} position={[5.905, 11.175, -25.263]} scale={0.417} />
          <mesh geometry={nodes.pCylinder143_lambert1_0.geometry} material={materials.lambert1} position={[-30.044, 0, 0.356]} />
          <mesh geometry={nodes.pCylinder147_blinn3_0.geometry} material={materials.blinn3} position={[-15.427, 5.968, 9.89]} rotation={[0, 0.281, 0]} scale={0.219} />
          <mesh geometry={nodes.pCylinder165_blinn3_0.geometry} material={materials.blinn3} />
          <mesh geometry={nodes.pCylinder165_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pCylinder180_blinn4_0.geometry} material={materials.blinn4} />
          <mesh geometry={nodes.pCylinder180_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pCylinder212_lambert1_0.geometry} material={materials.lambert1} position={[-17.172, 0.196, 8.571]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes.pCylinder214_lambert1_0.geometry} material={materials.lambert1} position={[-16.327, 0.196, 0.153]} rotation={[Math.PI, 0, Math.PI]} />
          <mesh geometry={nodes.pCylinder221_lambert1_0.geometry} material={materials.lambert1} position={[0, 0, 0.184]} />
          <mesh geometry={nodes.pCylinder223_blinn3_0.geometry} material={materials.blinn3} position={[0.731, 5.975, 6.099]} rotation={[0, 0, -Math.PI / 2]} scale={0.293} />
          <mesh geometry={nodes.pCylinder224_blinn3_0.geometry} material={materials.blinn3} position={[0.745, 6.528, 7.562]} rotation={[0, 0, 0.492]} scale={0.293} />
          <mesh geometry={nodes.pCylinder225_blinn3_0.geometry} material={materials.blinn3} position={[0.805, 6.528, 7.468]} rotation={[0, -0.772, 0.492]} scale={0.293} />
          <mesh geometry={nodes.pCylinder226_blinn3_0.geometry} material={materials.blinn3} position={[0.913, 6.528, 7.443]} rotation={[0, -1.544, 0.492]} scale={0.293} />
          <mesh geometry={nodes.pCylinder227_blinn3_0.geometry} material={materials.blinn3} position={[1.008, 6.528, 7.501]} rotation={[Math.PI, -0.825, -2.649]} scale={0.293} />
          <mesh geometry={nodes.pCylinder228_blinn3_0.geometry} material={materials.blinn3} position={[1.036, 6.528, 7.608]} rotation={[-Math.PI, -0.053, -2.649]} scale={0.293} />
          <mesh geometry={nodes.pCylinder229_blinn3_0.geometry} material={materials.blinn3} position={[0.981, 6.517, 7.705]} rotation={[-3.114, 0.725, -2.644]} scale={0.293} />
          <mesh geometry={nodes.pCylinder230_blinn3_0.geometry} material={materials.blinn3} position={[0.843, 6.528, 7.729]} rotation={[0, 1.432, 0.492]} scale={0.293} />
          <mesh geometry={nodes.pCylinder231_blinn3_0.geometry} material={materials.blinn3} position={[0.776, 6.528, 7.683]} rotation={[0, 0.879, 0.492]} scale={0.293} />
          <mesh geometry={nodes.pCylinder235_blinn3_0.geometry} material={materials.blinn3} />
          <mesh geometry={nodes.pCylinder235_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pCylinder239_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pCylinder240_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pCylinder252_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.pCylinder252_pasted__blinn5_0.geometry} material={materials.pasted__blinn5} />
          <mesh geometry={nodes.pCylinder252_pasted__blinn6_0.geometry} material={materials.pasted__blinn6} />
          <mesh geometry={nodes.pCylinder76_blinn3_0.geometry} material={materials.blinn3} position={[-15.298, 6.099, 6.853]} scale={0.388} />
          <mesh geometry={nodes.polySurface40_lambert1_0.geometry} material={materials.lambert1} position={[-14.073, 0, -1.234]} />
          <mesh geometry={nodes.polySurface636_lambert1_0.geometry} material={materials.lambert1} position={[21.083, 13.528, -25.263]} rotation={[0, 0, Math.PI]} scale={[0.417, 2.005, 0.417]} />
          <mesh geometry={nodes.polySurface657_lambert1_0.geometry} material={materials.lambert1} position={[-14.073, 0, -15.617]} />
          <mesh geometry={nodes.polySurface782_blinn4_0.geometry} material={materials.blinn4} />
          <mesh geometry={nodes.polySurface782_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.polySurface808_lambert1_0.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.polySurface878_pasted__blinn5_0.geometry} material={materials.pasted__blinn5} />
        </group>
      </group>
      <group position={[83.271, 4.496, 17.667]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.027, 0.019, 0.02]}>
        <group position={[28.017, 91.845, -2.733]}>
          <mesh
            onPointerEnter={(e) => setText('Bunsen Burner')}
            onPointerLeave={(e) => clear()}
            onClick={(e) => burnerClick()}
            geometry={nodes['flask_with_bright_liquid_Material_#3_0'].geometry} material={materials.Material_3} position={[-26.826, -48.721, 180.255 ]} />
          <mesh onPointerEnter={(e) => setText('Bunsen Burner')}
            onPointerLeave={(e) => clear()}
            onClick={(e) => burnerClick()} geometry={nodes['heat_mat_Material_#3_0'].geometry} material={materials.Material_3} position={[-27.851, -60.162, 10.514 ]} />
          <mesh onPointerEnter={(e) => setText('Bunsen Burner')}
            onPointerLeave={(e) => clear()}
            onClick={(e) => burnerClick()} geometry={nodes['lit_bunsen_burner_Material_#3_0'].geometry} material={materials.Material_3} position={[-26.777, -50.579, 16.984 ]} />
          <mesh onPointerEnter={(e) => setText('Bunsen Burner')}
            onPointerLeave={(e) => clear()}
            onClick={(e) => burnerClick()} geometry={nodes['tripod_with_wire_gauze_Material_#3_0'].geometry} material={materials.Material_3} position={[-26.874, -50.69, 146.592]} />
        </group>
      </group>
      <group position={[112.981, -0.174, -8.59]} rotation={[-Math.PI / 2, 0, -1.563]} scale={[24.96, 35.659, 46.071]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Chair_Chair_0.geometry} material={materials.Chair} position={[11.008, 5.154, 14.111]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Computer_Computer_0.geometry} material={materials.Computer} position={[10.997, 11.579, 7.341]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube002_Table_0.geometry} material={materials.Table} position={[0.027, 6.095, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube004_Bin_0.geometry} material={materials.material} position={[16.488, 0.686, 7.635]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh onPointerEnter={(e) => setText('Bunsen Burner')}
            onPointerLeave={(e) => clear()}
            onClick={(e) => burnerClick()} geometry={nodes.Cylinder_Mug_0.geometry} material={materials.material_3} position={[14.424, 11.018, 20]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[90.12, 18.788, 6.626]} rotation={[-Math.PI / 2, 0, 0]} scale={[13.379, 13.379, 8.815]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.499, 0.086, -0.501]} scale={0.03}>
            <mesh geometry={nodes.pPlane3_lambert1_0.geometry} material={materials['lambert1.001']} position={[0.069, -0.645, -0.679]} />
          </group>
        </group>
      </group>
      <group position={[78.956, 4.183, -7.753]} rotation={[-Math.PI / 2, 0, 0]} scale={31.482}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-2.054, 1.538, 8.034]} rotation={[1.531, -0.042, 0.742]}>
            <mesh geometry={nodes.Red_piette_NakedSingularity1_glass_0.geometry} material={materials.glass} position={[-4.029, -4.382, -0.238]} rotation={[0.008, -0.017, 0.388]} scale={0.735} />
            <mesh geometry={nodes.Red_piette_NakedSingularity1_plastic_red_0.geometry} material={materials.plastic_red} position={[-4.029, -4.382, -0.238]} rotation={[0.008, -0.017, 0.388]} scale={0.735} />
          </group>
        </group>
      </group>
      <group position={[94.471, 4.569, -4.499]} rotation={[-Math.PI / 2, 0, -1.589]} scale={6.265}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            onPointerEnter={(e) => setText('MicroScope')}
            onPointerLeave={(e) => clear()}
            onClick={(e) => scopeClick()}
            geometry={nodes.Microscope_Microscope_0.geometry} material={materials.Microscope} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[96.299, 4.552, -17.874]} rotation={[-Math.PI / 2, 0, -1.561]} scale={0.007}>
        <group position={[0, 0.001, 0]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, -0.001]}>
            <group position={[138.793, 98.896, -65.203]} rotation={[-1.439, 0, 0]} scale={[1.018, 1.018, 93.834]}>
              <mesh geometry={nodes.Cylinder008_Material003_0.geometry} material={materials['Material.021']} position={[-0.001, 0.005, 0]} />
            </group>
            <group position={[82.196, 98.445, -263.175]} rotation={[-1.764, 0, 0]} scale={[1.018, 1.018, 93.834]}>
              <mesh geometry={nodes.Cylinder009_Material003_0.geometry} material={materials['Material.021']} position={[-0.001, -0.001, 0]} />
            </group>
            <mesh geometry={nodes.Cube_Material_0.geometry} material={materials['Material.003']} position={[-0.211, 63.014, -27.555]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-7.505, -9.937, -63.543]} />
            <mesh geometry={nodes.Cube002__0.geometry} material={materials['Cube.002__0']} position={[126.23, 3.406, 39.641]} rotation={[-Math.PI / 2, 0, 0]} scale={[26.926, 19.071, 5.074]} />
            <mesh geometry={nodes.Cylinder_Material003_0.geometry} material={materials['Material.021']} position={[-0.789, 81.397, -60.995]} rotation={[-Math.PI / 2, 0, 0]} scale={[6.046, 6.046, 66.485]} />
            <mesh geometry={nodes.Cylinder001_Material003_0.geometry} material={materials['Material.021']} position={[-0.789, 81.397, -92.14]} rotation={[-Math.PI / 2, 0, 0]} scale={[6.046, 6.046, 66.485]} />
            <mesh geometry={nodes.Cylinder002_Material003_0.geometry} material={materials['Material.021']} position={[-0.789, 81.397, -118.473]} rotation={[-1.537, 0, 0]} scale={[6.046, 6.046, 66.485]} />
            <mesh geometry={nodes.Cylinder003_Material003_0.geometry} material={materials['Material.021']} position={[-0.789, 81.397, -142.043]} rotation={[-1.584, 0, 0]} scale={[6.046, 6.046, 66.485]} />
            <mesh geometry={nodes.Cylinder004_Material003_0.geometry} material={materials['Material.021']} position={[74.681, 52.36, -261.836]} rotation={[-Math.PI / 2, 0, 0]} scale={48.535} />
            <mesh geometry={nodes.Cylinder005_Material003_0.geometry} material={materials['Material.021']} position={[131.657, 50.287, -106.007]} rotation={[-Math.PI / 2, 0, 0]} scale={47.057} />
            <mesh geometry={nodes.Cylinder006_Material004_0.geometry} material={materials['Material.024']} position={[74.681, 52.36, -261.836]} rotation={[-Math.PI / 2, 0, 0]} scale={48.535} />
            <mesh geometry={nodes.Cylinder007_Material005_0.geometry} material={materials['Material.025']} position={[131.657, 50.287, -106.007]} rotation={[-Math.PI / 2, 0, 0]} scale={47.057} />
            <mesh geometry={nodes.Cylinder010_Material003_0.geometry} material={materials['Material.021']} position={[132.085, 7.043, 35.972]} rotation={[-Math.PI / 2, 0, 0]} scale={[45.278, 45.278, 6.146]} />
            <mesh geometry={nodes.Sphere_Material003_0.geometry} material={materials['Material.021']} position={[152.213, 42.846, 147.266]} rotation={[-Math.PI / 2, 0, 0]} scale={42.931} />
            <mesh geometry={nodes.Sphere001_Material013_0.geometry} material={materials['Material.031']} position={[152.213, 42.846, 147.266]} rotation={[-Math.PI / 2, 0, 0]} scale={42.931} />
          </group>
        </group>
      </group>
      <group position={[94.287, 4.22, 4.595]} rotation={[-Math.PI / 2, 0, -1.552]} scale={0.051}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              onPointerEnter={(e) => setText('Distillation Apparatus')}
              onPointerLeave={(e) => clear()}
              onClick={(e) => distillationClick()}
              geometry={nodes.defaultMaterial.geometry} material={materials.Distillation_Base_MAterial} />
            <mesh
              onPointerEnter={(e) => setText('Distillation Apparatus')}
              onPointerLeave={(e) => clear()}
              onClick={(e) => distillationClick()}
              geometry={nodes.defaultMaterial001.geometry} material={materials.Distillation_Glass_material} />
            <mesh
              onPointerEnter={(e) => setText('Distillation Apparatus')}
              onPointerLeave={(e) => clear()}
              onClick={(e) => distillationClick()}
              geometry={nodes.defaultMaterial002.geometry} material={materials.Distillation_Screen} />
          </group>
          <mesh geometry={nodes.defaultMaterial003.geometry} material={materials.Distillation_Base_MAterial} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[79.776, 4.356, 7.248]} rotation={[-Math.PI / 2, 0, 0]} scale={0.597}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0.002, 0, 0]}>
            <mesh geometry={nodes.becher_Material_0.geometry} material={materials['Material.032']} position={[27.22, 0, -259.087]} rotation={[-Math.PI / 2, 0, 0]} scale={68.653} />
            <mesh geometry={nodes.becher_liquide_Material003_0.geometry} material={materials['Material.033']} position={[27.22, 0, -259.087]} rotation={[-Math.PI / 2, 0, 0]} scale={68.653} />
            <mesh geometry={nodes.fiole_Material_0.geometry} material={materials['Material.032']} position={[37.805, 0, 44.811]} rotation={[-Math.PI / 2, 0, 0]} scale={16.476} />
            <mesh geometry={nodes.fiole_liquide_Material004_0.geometry} material={materials['Material.034']} position={[37.805, 0, 44.811]} rotation={[-Math.PI / 2, 0, 0]} scale={16.476} />
            <mesh geometry={nodes.flacon_Material_0.geometry} material={materials['Material.032']} position={[-209.806, 0, -122.481]} rotation={[-Math.PI / 2, 0, 0]} scale={37.568} />
            <mesh geometry={nodes.flacon_liquide_Material002_0.geometry} material={materials['Material.035']} position={[-209.806, 0, -122.481]} rotation={[-Math.PI / 2, 0, 0]} scale={37.568} />
          </group>
        </group>
      </group>
      <group position={[99.95, 4.724, 4.712]} rotation={[-Math.PI / 2, 0, -3.138]} scale={0.065}>
        <mesh

          onPointerEnter={(e) => setText('MicroScope')}
          onPointerLeave={(e) => clear()}
          onClick={(e) => scopeClick()} geometry={nodes.Microscope_Lab_devices_0.geometry} material={materials.Lab_devices} rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[113.729, 4.369, 5.299]} rotation={[-Math.PI / 2, 0, -1.534]} scale={0.829}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 0, 0.002]}>
            <group position={[0, 0, -94.763]} rotation={[0, 1.571, 0]} scale={123.801}>
              <mesh geometry={nodes.Circle_metal_1_0.geometry} material={materials.metal_1} />
              <mesh geometry={nodes.Circle_metal_2_0.geometry} material={materials.metal_2} />
            </group>
            <group position={[0, 381.812, -82.657]} rotation={[-0.229, 0, 0]} scale={100}>
              <mesh geometry={nodes.Plane001_digital_display_sides_0.geometry} material={materials.digital_display_sides} />
              <mesh geometry={nodes.Plane001_digital_displays_0.geometry} material={materials.digital_displays} />
            </group>
            <group position={[0, 28.869, 312.192]} rotation={[-1.469, 0, 0]} scale={100}>
              <mesh geometry={nodes.Plane002_digital_display_sides_0.geometry} material={materials.digital_display_sides} />
              <mesh geometry={nodes.Plane002_digital_displays_0.geometry} material={materials.digital_displays} />
            </group>
          </group>
        </group>
      </group>
      <group position={[84, 0.01, 8.516]} rotation={[-Math.PI / 2, 0, 0]} scale={0.88}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.stoolbase_0.geometry} material={materials.metal} />
          <mesh geometry={nodes.stoolbase_1.geometry} material={materials.pillow} />
        </group>
      </group>
      <group position={[83.316, 0.093, -5.141]} rotation={[-Math.PI / 2, 0, 0]} scale={0.933}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.stoolbase_0001.geometry} material={materials['metal.001']} />
          <mesh geometry={nodes.stoolbase_1001.geometry} material={materials['pillow.001']} />
        </group>
      </group>
      <group position={[103.2, -0.074, 5.047]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.stoolbase_0002.geometry} material={materials['metal.002']} />
          <mesh geometry={nodes.stoolbase_1002.geometry} material={materials['pillow.002']} />
        </group>
      </group>
      <group position={[90.524, -0.151, -5.043]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.stoolbase_0003.geometry} material={materials['metal.003']} />
          <mesh geometry={nodes.stoolbase_1003.geometry} material={materials['pillow.003']} />
        </group>
      </group>
      <group position={[112.981, -0.174, -8.59]} rotation={[-Math.PI / 2, 0, -1.563]} scale={[24.96, 35.659, 46.071]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Chair_Chair_0001.geometry} material={materials['Chair.001']} position={[11.008, 5.154, 14.111]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[115.107, -0.174, 2.381]} rotation={[-Math.PI / 2, 0, -1.563]} scale={[24.96, 35.659, 46.071]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Chair_Chair_0002.geometry} material={materials['Chair.002']} position={[11.008, 5.154, 14.111]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.020']} position={[96.821, -0.157, 0.086]} rotation={[0, 0, -Math.PI]} scale={[1.119, 0.272, 1.119]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[96.696, -0.174, 0.256]} rotation={[-Math.PI, 0, 0]} scale={[-20.634, -63.687, -19.691]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.002']} position={[113.515, 7.87, 18.504]} rotation={[1.642, 0, 3.114]} scale={2.387} />
      <mesh geometry={nodes.Torus.geometry} material={materials['Material.004']} position={[111.091, 0.272, 17.841]} scale={1.008} />
    </group></RigidBody>
  )
}

useGLTF.preload('/chemLabFinal.glb')
