/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 corridorBiology.glb 
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { Route, Routes, useNavigate } from 'react-router-dom';

export function CorridorBiology(props) {
  const { nodes, materials } = useGLTF('/corridorBiology.glb')
  return (
    <RigidBody type='fixed' colliders="trimesh">
    <group {...props} dispose={null} position={[0, -10, 0]} scale={[3,5,3]}>
      <group scale={0.01}>
        <group position={[2401.575, 0, -220.033]}>
          <mesh geometry={nodes.Object_29.geometry} material={materials.Flag_of_Washington} position={[-2040.238, 70.243, -484.286]} />
          <group position={[-2048.818, 34.447, -431.194]}>
            <group position={[-11.08, 11.273, -86.51]}>
              <mesh geometry={nodes.Object_33.geometry} material={materials.Metal_Corrogated_Shiny} />
              <mesh geometry={nodes.Object_36.geometry} material={materials.Metal_Corrogated_Shiny} />
            </group>
          </group>
        </group>
        <group position={[2401.575, 0, -220.033]}>
          <mesh geometry={nodes.Object_6.geometry} material={materials.M_MainHall_Atlas} position={[-757.478, 0, -524.58]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.M_RoomWallTrim} position={[-757.478, 0, -524.58]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.M_MainHall_Atlas} position={[-757.478, 0, -524.58]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.M_MainHall_Atlas} position={[-757.478, 0, -524.58]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.M_WallCarpetPanel} position={[-757.478, 0, -524.58]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.Color_M07} position={[-757.478, 0, -524.58]} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.Light_MetalDark} position={[-757.478, 0, -524.58]} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.Light_MetalDark} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.M_MainHall_Atlas} position={[-757.478, 0, -524.58]} />
        </group>
        <group position={[2401.575, 0, -220.033]}>
          <mesh geometry={nodes.Object_25.geometry} material={materials.M_MainHall_Atlas} position={[-1897.462, 641.299, -302.862]} />
        </group>
        <group position={[2401.575, 0, -220.033]}>
          <group position={[-2395.373, 270.674, 1078.478]}>
            <mesh geometry={nodes.Object_41.geometry} material={materials.Color_A05} />
            <mesh geometry={nodes.Object_42.geometry} material={materials.Metal_Aluminum_Anodized} />
            <mesh geometry={nodes.Object_43.geometry} material={materials.Color_G02} />
          </group>
          <group position={[-2053.036, 45.507, -498.213]}>
            <mesh geometry={nodes.Object_54.geometry} material={materials.M_Flagpole} position={[0.156, 117.058, 0.888]} />
          </group>
          <group position={[-2731.574, 45.507, -498.213]}>
            <mesh geometry={nodes.Object_57.geometry} material={materials.M_Flagpole} position={[0.156, 117.058, 0.888]} />
          </group>
          <group position={[-2392.761, 319.029, 162.966]}>
            <mesh geometry={nodes.Object_110.geometry} material={materials.M_MainHall_Atlas} />
            <mesh geometry={nodes.Object_111.geometry} material={materials.Color_M04} />
          </group>
          <mesh geometry={nodes.Object_39.geometry} material={materials.M_MainHall_Atlas} position={[-2392.761, 171.45, 625.088]} />
          <mesh geometry={nodes.Object_45.geometry} material={materials.M_MainHall_Atlas} position={[-2381.877, 567.366, 317.079]} />
          <mesh geometry={nodes.Object_49.geometry} material={materials.M_MainHall_Atlas} position={[-2397.808, 102.705, -523.433]} />
          <mesh geometry={nodes.Object_51.geometry} material={materials.M_MainHall_Atlas} position={[-2397.294, 239.69, 277.248]} />
          <mesh geometry={nodes.Object_59.geometry} material={materials.M_MainHall_Atlas} position={[-2392.759, 106.426, 302.035]} />
          <mesh geometry={nodes.Object_63.geometry} material={materials.M_MainHall_Atlas} position={[-2392.761, 583.871, 277.266]} />
          <mesh geometry={nodes.Object_65.geometry} material={materials.M_MainHall_Atlas} position={[-2381.781, 538.798, 301.873]} />
          <mesh geometry={nodes.Object_67.geometry} material={materials.M_MainHall_Atlas} position={[-2370.401, 579.728, 304.205]} />
          <mesh geometry={nodes.Object_69.geometry} material={materials.M_MainHall_Atlas} position={[-2381.435, 532.453, 313.951]} />
          <group position={[-2606.803, 101.546, -322.782]}>
            <mesh geometry={nodes.Object_72.geometry} material={materials.Color_M08} />
            <mesh geometry={nodes.Object_73.geometry} material={materials.lambert2} />
            <mesh geometry={nodes.Object_74.geometry} material={materials.M_MonitorScreen} />
          </group>
          <mesh geometry={nodes.Object_76.geometry} material={materials.M_MainHall_Atlas} />
          <group position={[-2392.761, 309.88, -523.31]}>
            <mesh geometry={nodes.Object_79.geometry} material={materials.M_BlackFrame} />
            <mesh geometry={nodes.Object_80.geometry} material={materials.M_MonitorScreen} />
          </group>
          <group position={[-3568.305, 310.833, -523.31]}>
            <mesh geometry={nodes.Object_82.geometry} material={materials.M_MonitorScreen} />
            <mesh geometry={nodes.Object_83.geometry} material={materials.M_BlackFrame} />
          </group>
          <group position={[-1218.488, 310.833, -523.31]}>
            <mesh geometry={nodes.Object_85.geometry} material={materials.M_MonitorScreen} />
            <mesh geometry={nodes.Object_86.geometry} material={materials.M_BlackFrame} />
          </group>
          <group position={[-762.558, 189.23, 776.935]}>
            <mesh geometry={nodes.Object_91.geometry} material={materials.M_BlackFrame} />
            <mesh geometry={nodes.Object_92.geometry} material={materials.M_MonitorScreen} />
          </group>
          <group position={[-4022.965, 189.23, 796.538]}>
            <mesh geometry={nodes.Object_94.geometry} material={materials.M_BlackFrame} />
            <mesh geometry={nodes.Object_95.geometry} material={materials.M_MonitorScreen} />
          </group>
          <group position={[-4022.965, 189.23, -122.934]}>
            <mesh geometry={nodes.Object_97.geometry} material={materials.M_BlackFrame} />
            <mesh geometry={nodes.Object_98.geometry} material={materials.M_MonitorScreen} />
          </group>
          <mesh geometry={nodes.Object_88.geometry} material={materials.M_BlackFrame} position={[-762.558, 189.23, -117.545]} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.M_MainHall_Atlas} position={[-2393.178, 242.57, -111.671]} />
          <mesh geometry={nodes.Object_102.geometry} material={materials.M_MainHall_Atlas} position={[-2393.32, 62.054, -402.66]} />
          <mesh geometry={nodes.Object_104.geometry} material={materials.Color_M04} position={[-2392.761, 606.368, 271.368]} />
          <mesh geometry={nodes.Object_106.geometry} material={materials.M_MainHall_Atlas} position={[-2392.834, 377.47, 320.455]} />
          <mesh geometry={nodes.Object_108.geometry} material={materials.M_MainHall_Atlas} position={[-2392.627, 91.44, 333.321]} />
        </group>
      </group>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-0.706, -0.146, 0.02]} scale={[1, 0.089, 1]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.004']} position={[-5.058, 3.752, 8.567]} rotation={[1.579, 0, -3.129]} scale={0.351} />
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.004']} position={[5.896, 3.752, 8.567]} rotation={[1.579, 0, -3.129]} scale={0.351} />
      <mesh geometry={nodes.Text002.geometry} material={materials['Material.007']} position={[16.308, 1.985, -4.173]} rotation={[1.571, 0.009, 1.575]} scale={0.436} />
      
      <Float
          speed={3} // Animation speed, defaults to 1
          rotationIntensity={0} // XYZ rotation intensity, defaults to 1
          floatIntensity={1} // Up/down float intensity, works like a multiplier with floatingRange,defaults to 1
          floatingRange={[0, 0.3]} >
        <RigidBody type="fixed" sensor onIntersectionEnter={()=>{console.log("jkn"); window.location.href = '/Digestive';}}>
      <mesh geometry={nodes.Torus006.geometry} material={materials['Material.008']} position={[15.217, 0.104, -1.074]} scale={0.483} />
      </RigidBody>
      {/* <RigidBody type="fixed" sensor onIntersectionEnter={()=>{console.log("jkn"); window.location.href = './';}}> */}
      <mesh geometry={nodes.Torus001.geometry} material={materials['Material.008']} position={[-5.397, 0.104, 7.621]} scale={0.483} />
      {/* </RigidBody> */}
      </Float>
    </group>
   </RigidBody>
  )
}

useGLTF.preload('/corridorBiology.glb')
